docs/writing_tests.md
Although there are "sandstone" references throughout the codebase, let's
be consistent about OpenDCDiag framework and tests in our documentation.
=> docs: writing_tests: remove sandstone refs

framework/cpuid_internal.h
Depending on build flags, LOG_LEVEL_QUIET may be used. That define is in
sandstone_p.h, so let's include it.
=> FW: cpuid_internal: include sandstone_p

framework/cpuid_internal.h, framework/main.cpp
With this implementation, we will only issue the new system call if
CPUID indicates AMX support, in which case we ignore XCR0. This is
designed for the likely scenario of AMX-capable kernels being used for
AMX-capable hardware. If, instead, we're running on a system that fails
to enable all CPU features, they won't begrudge us a few more CPU cycles
to find out.
We should also support the case in which the 5.16+ Linux kernel does
support AMX but refuses to offer it to us. For that case, we expect the
ARCH_GET_XCOMP_SUPP call to tell us "no AMX".
=> FW/CPUID: add support for Linux 5.16 state saving requests

.github/scripts/check-no-tabs.sh, .github/workflows/pr.yaml
The script only checks if there were no tabs added in the changeset.
=> Add simple lint script.

framework/unit-tests/test_knob_tests.cpp
I recently got nipped by this when using an older version of gcc. This
should fix errors about find_if not being part of std::.
=> unit-tests: #include <algorithm> in test_knob_tests

framework/sysdeps/unix/child_debug.cpp
The output of "code=??" is not useful. And since the Linux kernel is lazy and doesn't have constants for everything (it's not like we're running out of numbers), include the hardware trap information too.
```yaml
- { level: error, text: 'E> Received signal 4 (Illegal instruction) code=2 (ILL_ILLOPN), RIP = 0x44e1a0, trap=6 (UD), error_code = 0x0' }
- { level: error, text: 'E> Received signal 8 (Floating point exception) code=1 (FPE_INTDIV), RIP = 0x44e1bc, trap=0 (DE), error_code = 0x0' }
- { level: error, text: 'E> Received signal 7 (Bus error) code=2 (BUS_ADRERR), RIP = 0x44e22a, CR2 = 0x7f5f2b9ea000, trap=14 (PF), error_code = 0x4' }
- { level: error, text: 'E> Received signal 11 (Segmentation fault) code=1 (SEGV_MAPERR), RIP = 0x44e271, CR2 = 0xfffffffffc0005be, trap=14 (PF), …
```
=> FW/Unix: update the information logged on crashes

framework/sandstone.h, framework/selftest.cpp, framework/test_selectors/WeightedSelectorBase.h, framework/topology.h
This is not complete and Clang is not officially supported. These are just a couple of changes I'd done anyway, so I might as well upstream.
Clang didn't like some of the inline assembly we had for GCC. This is the only build error. Everything else was just annoyance (warnings).
=> Clang fixes

framework/forkfd/forkfd_freebsd.c, framework/logging.cpp, framework/main.cpp, framework/sandstone.cpp, framework/sandstone_context_dump.cpp, framework/sandstone_iovec.h, framework/sandstone_p.h, framework/sysdeps/freebsd/cpu_affinity.cpp, framework/sysdeps/freebsd/malloc.cpp, framework/sysdeps/freebsd/meson.build, framework/sysdeps/freebsd/thermal_monitor.hpp, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/unix/tmpfile.c, framework/topology.h, meson-freebsd.ini, meson.build
This PR adds a series of commits that, as far as I can tell, make OpenDCDiag compile and run properly on FreeBSD. I've only tested with GCC 10 (installed from the ports tree), which is the compiler that we support for Linux and Windows too.
The majority of commits are build fixes, correcting improper assumptions of Linux behaviour in the Unix code, such as using `splice(2)` (a Linux-specific system call) or Linux-specific constants elsewhere. There are also fixes to existing FreeBSD functionality that wasn't correct or was incomplete, because it had never been compiled or run. Finally, it turns out that FreeBSD does have memfds, so that is enabled for it.
=> FreeBSD port

framework/selftest.cpp, framework/sysdeps/unix/child_debug.cpp
```yaml
messages:
- { level: error, text: 'E> Received signal 5 (Trace/breakpoint trap) code=128 (SI_KERNEL), RIP = 0x44e29f, CR2 = (nil)' }
- level: warning
text: |1
W> #4  cause_sigtrap_int3 () at ../../../src/arkose/arkose-one/opendcdiag/framework/selftest.cpp:423
423	}
=> 0x44e29f <cause_sigtrap_int3()+5>:	nop
```
The disassembly points to the next instruction, but oh well.
=> FW/Unix: add signal debugging for SIGTRAP too

meson_options.txt, tests/meson.build
Cleans up how folks configure library dependency links. Pass
'-Ddependency_link=static' if that is your preference.
Only influences dependency() static_link behavior. A riff on meson's
default_library core option.
=> meson: add dependency_link option

framework/logging.cpp, meson-cross-win32.ini, meson.build
This needs to be added to the CI. The build was failing because we are using `gmtime_r`, which MinGW implements as an inline function in time.h but only if the `_POSIX_C_SOURCE` macro is defined.
=> Fix Windows builds & add toolchain file

framework/logging.cpp, framework/meson.build, framework/sandstone.cpp, framework/sandstone.h, framework/sandstone_context_dump.cpp, framework/sandstone_context_dump.h, framework/sandstone_data.h, framework/sandstone_p.h, framework/sandstone_sections.S, framework/sandstone_test_groups.cpp, framework/sandstone_utils.cpp, framework/selftest.cpp, framework/sysdeps/darwin/cpu_affinity.cpp, framework/sysdeps/darwin/malloc.cpp, framework/sysdeps/darwin/meson.build, framework/sysdeps/darwin/pthread_barrier.cpp, framework/sysdeps/darwin/pthread_barrier.h, framework/sysdeps/darwin/thermal_monitor.hpp, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/unix/stacksize.cpp, meson-darwin.ini, meson.build
Complementing now the FreeBSD port, this is the macOS port. This PR allows OpenDCDiag to run on a macOS system, but due to the lack of an affinity-setting API, the **macOS port is not reliable**.
But it does run:
```
$ ./opendcdiag -o- | awk '(NR > 1 && NR < 6) || /exit:/'
command-line: 'opendcdiag -o-'
version: opendcdiag-e6b8da7dc018
os: Darwin 19.6.0
timing: { duration: 1000.000, timeout: 300000.000 }
exit: pass
```
=> macOS port

.github/workflows/pr.yaml
Currently there's no easy way to allow a job running if dependency is
either success or skipped. See https://github.com/actions/runner/issues/491
=> CI: Explicitily specify when the workflow should build.

.github/workflows/pr.yaml
It will not work for PRs from forked repos (no ref will be found).
=> CI: disable git-sanity check temporarily.

framework/sysdeps/unix/child_debug.cpp
The thr_self() function is defined in sys/thr.h, so we'll include it.
Without it, OpenDCDiag may not build on FreeBSD.
Bumped into this compiler error when I attempted to compile on FreeBSD
13.0 with GCC-11.
=> FW: child_debug: add missing FreeBSD include

docs/writing_tests.md, framework/sandstone.cpp
By specifying --max-test-loop-count=0.  Previously, this option was allowed by the framework but it had no effect.  This PR changes this behaviour so that it essentially has the effect of disabling test fracturing and making test execution time limited (rather than loop count limited).
=> [FW] Allow fracturing to be disabled on the command line

framework/test_selectors/TestrunSelectorBase.h
Avoids compiler warnings for nonvirtual destructors, and potential
memory leaks
Signed-off-by: Kevin Boyd<kevinboyd@google.com>
=> Make Test Selector base destructor virtual

.github/scripts/check-git-history.sh, .github/workflows/pr.yaml
This version uses the right ancestor to the merge that the checkout
github action fetches as opposed to assuming the branch is in the same
repository.
=> CI: enable git sanity.

framework/sandstone_data.h, framework/sandstone_utils.cpp
The constants and types we were using were not reliable.
=> FW/Data: fix again the detection of FP16 and FP128

framework/sandstone.cpp
Keep them in a single place (outside of the selftests, at least) and use the GCC built-in to generate it.
=> FW: clean up our uses of ud2 instruction

framework/sysdeps/linux/effective_cpu_freq.hpp
_rdtscp is in ia32intrin.h, which isn't included by immintrin.h with
GCC 10.
=> FW/linux: fix build with GCC 10

meson.build
Because C allows this:
```c
void f(int *x);
void g(const int *x)
{ f(x); }
```
=> Meson: add -Werror=discarded-qualifiers to the C flags

tests/eigen_sparse/eigen_sparse.cpp, tests/eigen_svd/svd.cpp, tests/eigen_svd/svd_double.cpp, tests/eigen_svd/svd_fvectors.cpp, tests/eigen_svd_jacobi/svd.cpp, tests/eigen_svd_jacobi/svd_cdouble.cpp, tests/eigen_svd_jacobi/svd_double.cpp, tests/eigen_svd_jacobi/svd_fvectors.cpp, tests/meson.build
These tests do not contain any Haswell-specific code (read: AVX2 or
FMA), so they don't need to be in the tests_hsw library. That library
should be used only for tests that always require HSW.
This does not change the default OpenDCDiag binary contents, because we
default to `-march=haswell` anyway. However, it does make these tests
available for the other (`-march=westmere`) build.
=> Eigen: move HSW tests into the baseline

framework/cpuid_internal.h, framework/interrupt_monitor.hpp, framework/random.cpp, framework/sandstone.cpp, framework/sandstone.h, framework/sandstone_context_dump.cpp, framework/sandstone_data.h, framework/selftest.cpp, framework/sysdeps/linux/effective_cpu_freq.hpp, framework/sysdeps/linux/meson.build, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/unix/splitlock_detect.c, framework/topology.cpp, meson.build, meson_options.txt, tests/meson.build
This allows building OpenDCDiag for a non-x86-64 platform. No guarantees this passes the selftests or does anything useful, but it at least compiles.
=> Isolate x86-64 specific content

framework/main.cpp, framework/sandstone.cpp
Both Linux and Windows execute the init constructors in a specific order
which we can hook into. And Linux's init-time constructors get argv too,
so we can do the fallback trick if we need to.
=> FW: make the Sandstone before-main() code runs really early

framework/meson.build
* Use of "cygwin" build target in meson
If user uses meson package provided with python from MSYS repo (not
MINGW64) for configuration Python's sys.platform is set to "cygwin".
Meson declares to support Cygwin as a target and makes project
configuration frictionless under MSYS environment. This unfortunetly
means we have to check for "cygwin" target during meson configuration
when we check for "windows" targets, but makes configuration much
easier.
=> Adding support for native building on Windows using MSYS.

framework/simd.conf
Enabling two instructions in simd.conf: movdiri and movdir64b.
Signed-off-by: Dawid Sabat <dawid.sabat@intel.com>
=> Enabling movdiri and movdiri64b instructions.

framework/sandstone.cpp
The timeout is 20 seconds, but `(20s).count()` returns the number 20. The
Win32 API expects milliseconds, so we were waiting for 20 milliseconds.
=> FW/Win32: fix the timeout of waiting for hung tests

framework/sandstone.cpp
This can happen if sys_clone() fails (see #62) due to the kernel
rejecting CLONE_PIDFD. This may need to be handled in
detect_clone_pidfd_support() inside forkfd_linux.c itself, eventually,
but there's no harm in falling back if clone() failed and fork() doesn't
fail. Maybe we're out of file descriptors?
=> FW: Handle forkfd() failing without FFD_USE_FORK

framework/forkfd/forkfd_linux.c
Reading the kernel sources, I was sure we'd get an ECHILD if the child
hadn't exited yet, but that's not the case. We only get ECHILD if the
current process has no child processes. But if we do have one and the
one we're waiting for hasn't exited, waitid() returns 0.
So let's not attempt to correct it with `forkfd_wait()` or `forkfd_wait4()`.
Those have "wait" in the name, so they should behave exactly the same
way. The man pages say:
```
waitpid(): if WNOHANG was specified and one or more child(ren)
specified by pid exist, but have not yet changed state, then 0 is
returned.
waitid(): returns 0 on success or if WNOHANG was specified and no
child(ren) specified by id has yet changed state
```
OpenDCDiag does not use this code path (blocking mode forkfd only).
Matching Qt change: …
=> forkfd: don't attempt to guess EWOULDBLOCK when WNOHANG is active

framework/sandstone.cpp, framework/selftest.cpp
When a test is split into several slices due a limit imposed by
"max_threads" flag, we need to consider this extra runtime when
calculating timeout.
=> framework: Consider slices count when calculating test timeout.

framework/sandstone.cpp
The debug message logged by the framework when a kvm tests uses a
custom init method crashes, as it is called before logging has been
initialised.  In addition, it's of limited informational value, so
it's better to simply remove it.
Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>
=> fw: vmx: remove debug log

framework/sandstone.h, framework/sandstone_kvm.h, framework/sysdeps/linux/kvm.c
In order to write richer KVM content, we'll need (imho) more context provided to the exit handler. This series has the generic_run function pass `struct kvm_ctx`, `struct test`, and `cpu` info/state to the handler.
I'm fine with squashing these-- broke them up to help with review.
=> Add context to exit handler

framework/sandstone_kvm.h, framework/selftest.cpp, framework/sysdeps/linux/kvm.c
This commit adds two new optional kvm handlers that can be used to
initialise a VM before the payload is run and to access the state
of the VM after the payload has finished executing.
A new selftest is also added to test the new handlers.
Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>
=> fw: kvm: Add setup and check handlers

framework/sysdeps/linux/kvm.c
It's better to signal an error in a KVM test by letting the functions
unwind naturally rather than cancelling the thread.  This allows the
framework to cleanup the VMs it's created and crucially to report
the error more quickly.  It takes the framework 3.5 seconds to report
the failure of a simple test on my test machine when the failure is signalled via
report_fail_msg.  After this patch, the failure is reported in 400ms.
The problem can be reproduced using the selftests, e.g.,
opendcdiag --selftests -e kvm_prot_64bit_fail
Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>
=> fw: kvm: don't use report_fail_msg

framework/selftest.cpp
It's a good self-test, but it's best for it to stand alone. Its
execution time can increase as core count increases. By dropping this
test from the @positive group, someone (like myself) wishing to run
@positive under strict constraints, especially timing, will no longer
have to account for a "long pole" self-test.
=> fw: selftest: drop maxthreads1 from positive group

framework/sysdeps/unix/child_debug.cpp
Following outcome of static code analysis, fixing an off by one error, where string null termination character was written outside of string's buffer.
=> Fixing off by one in gdb backtrace

framework/sandstone.cpp, framework/sysdeps/freebsd/cpu_affinity.cpp, framework/sysdeps/linux/cpu_affinity.cpp, framework/sysdeps/windows/cpu_affinity.cpp, framework/topology.cpp
We used to do that before March 2021, but thought better of it.
Unfortunately, I accidentally brought it back when I wrote the
abstracted sysdeps/*/cpu_affinity.cpp when I moved the thread naming
functionality into pin_to_logical_processor().
As a consequence, on Unix systems, run_threads() starts each of the
worker threads with the same affinity, so they're all competing for CPU
time on the same processor. They'll eventually move themselves off to
another CPU, but not without a lot of context-switching. On systems with
100+ logical processors (such as dual-socket CLX and ICX), that's a lot
of contention.
=> Fix control thread pinning

tests/meson.build
Passing march_flags followed by -march=skylake-avx512 is usually
fine... except that march_flags had -mtune-skylake and that has an
effect. We don't want non-AVX512 tuning for AVX512 code, so let GCC the
best tuning for it.
For AVX2 code, we do want -mtune=skylake, as there are a lot of those
out there, both in Xeon form (Xeon D, E and W) and in client form. At
some point in the future, we may want to switch to -mtune=alderlake,
but we're not there yet.
=> Buildsystem: fix passing -march flags to the HSW and SKX libraries

tests/ifs/ifs.c
* Use `fork()` + `exec()` instead of `system()`
* Only build it on Linux/x86-64
* Don't produce errors if the /sys interface is already present
* Bump it to production quality
=> intel_ifs: cleanups and make product-quality

tests/ifs/ifs.c
It is either telling us that the module doesn't exist or that we don't
have permissions to load it. Neither is a fatal issue so we shouldn't
let this be shown in logging verbosity 1.
According to kernel developers, the module should be auto-loaded on
machines that have IFS support, so the modprobe shouldn't even be
needed. However, on the machines we tested, that autoloading was somehow
broken, so we're choosing to leave it in.
=> ifs: suppress modprobe's error if it can't find the module

docs/writing_tests.md
Was playing around opendcdiag. Encountered "Failed build" issue when adding the following test case.
```
tests_base_skx_set.add(
'examples/vector_add.c'
)
```
Pasting the error message.
```Checking for type "_Float16" : YES (cached)
Checking for type "_Float16" : YES (cached)
Checking for type "__fp16" : NO (cached)
**../tests/meson.build:42:19: ERROR: Unknown variable "tests_base_skx_set".**
A full log can be found at /home/xxxx/DilipMain/OpenDCDiag/DilipDCDiag/builddir/meson-logs/meson-log.txt
FAILED: build.ninja
/usr/bin/meson --internal regenerate /home/xxxx/DilipMain/OpenDCDiag/DilipDCDiag
```
Resolved by removing `base` in `test_base_skx_set.add`.
=> modified docs/writing_tests.md to correct build errors

tests/ifs/ifs.c
The sysfs API that was accepted into 5.19 differs slightly from the preliminary API that this code was written for.
This includes support for future "intel_ifs_#" tests and handles the timeout error codes.
Docs: https://docs.kernel.org/x86/ifs.html
=> intel_ifs driver update

framework/meson.build, framework/sandstone_config.h.in
First time around, I wasn't setting SANDSTONE_DEBUG correctly. Silly me.
Then, it was realized that SANDSTONE_DEBUG wasn't necessary. So, brought back DEBUG and preprocessor handling for the DEBUG, NDEBUG macros in sandstone_config.h.
=> meson: correct DEBUG, NDEBUG handling

framework/forkfd/forkfd.c, framework/forkfd/forkfd.h, framework/forkfd/forkfd_freebsd.c, framework/forkfd/forkfd_linux.c
fork() works by implementing Copy-On-Write for all pages that either the
parent or the child process write to. So if the parent process continues
running while the child is between fork(2) and execve(2), then it will
keep causing page faults and requiring the OS to duplicate those pages,
with the accompanying page table update and a TLB flush. This problem
is aggravated if the parent process is multithreaded, as the simple act
of running in the parent will cause those threads' stacks to cause page
faults.
The BSD solution for that was vfork(), which has two differences in
behavior: it blocks the parent from running and it shares memory with
it. But it's always been tricky, so POSIX.1-2001 deprecated it and 2008
removed its definition completely. Because it is still sharing the same
pages, …
=> forkfd: implement vfork(2) support

framework/logging.cpp, framework/meson.build, framework/sandstone.cpp, framework/sandstone_config.h.in, framework/sandstone_p.h, meson_options.txt
We have multiple builds of our internal tool and we actually have a good CI process where everything gets build from the same source... but then we can't tell apart runs from different builds by just looking at the logs. So add a way for providing suffixes.
```
$ meson configure -Dversion_suffix=thiago
$ ninja
[48/48] Linking target opendcdiag
$ ./opendcdiag --version
opendcdiag-3a84c774ec3e-thiago
```
=> FW: add a way to specify a version suffix

framework/logging.cpp, framework/meson.build, framework/sandstone_config.h.in, framework/scripts/make-gitid.pl, meson.build
Partially reverts commit 6e7b7a44a5c7bd53565b35a0a53d9df4da0ab96f (PR #101),
which added the concept of version suffix, but it was inserted in the
incorrect place for tagged releases.
For example:
```
$ git tag opendcdiag-2459761.5
$ git archive @ : | tar -x .hash
$ cat .hash
ea83aacaa2302d36f6fc5c3572d71f85963d166d HEAD -> main, tag: opendcdiag-2459761.5
```
That used to produce:
```c
#define GIT_ID "v2459761.5 (ea83aacaa2302d36f6fc5c3572d71f85963d166d)"
```
Which would result in OpenDCDiag printing:
```yaml
version: v2459761.5 (ea83aacaa2302d36f6fc5c3572d71f85963d166d)-foobar
```
This commit moves it to the right place:
```c
#define GIT_ID "v2459761.5-foobar (ea83aacaa2302d36f6fc5c3572d71f85963d166d)"
```
=> Meson: fix the version suffix when the commit is tagged

framework/cpuid_internal.h, framework/main.cpp, framework/sandstone.cpp, framework/sandstone_p.h
Benefits:
* Can use the loaded CPU info from load_cpu_info()
* Runs after the command-line is processed, so --version and --help work
* Adds some code after the execution, to maybe modify it
=> FW: move the CPU-supported checking into sandstone_main()

framework/sandstone.cpp
Restricted != Inexistent. Some options were supported by the Intel
DCDiag tool that was based off an early version of this codebase. Bring
them back.
=> FW: add some options to the OpenDCDiag restricted command-line mode

framework/meson.build, framework/sysdeps/linux/meson.build, meson.build
* fix the warning of a missing kwarg to `run_command¹
* stop abusing the input file array for `configure_file¹
* add a comment explaining why we use `configure_file`
* fix the project name
=> Meson cleanups

framework/logging.cpp, framework/meson.build, meson.build, meson_options.txt
* Moved `SANDSTONE_EXECUTABLE_NAME` and `SANDSTONE_FALLBACK_EXEC` into sandstone_config.h
* Moved two very uncommon settings to `framework_config` array (arrays are actually hard to set...)
* Opportunistically fixed one missing use of `PROGRAM_VERSION`
=> Make better use of sandstone_config.h and the meson -D options

framework/logging.cpp, framework/main.cpp, framework/meson.build, framework/sandstone_config.h.in, meson.build
* move two more -D options to sandstone_config.h
* fix accidental inverted condition for restricted command-lines
=> Meson: more fixes

framework/sandstone.cpp
This forgot to multiply by the size of the object, so the compiler produced a warning that we left a byte unchanged. And it inverted source and destination, as evidenced by the fact that overwrote the first timestamp after the `memmove()`.
So use `std::move()` to be clearer. The compiler emits `memmove()` anyway after optimisations kick in, because `std::chrono::duration` has a trivial destructor and copy/move constructor.
```
framework/sandstone.cpp: In function ‘void background_scan_update_timestamps()’:
framework/sandstone.cpp:2979:12: warning: ‘void* memmove(void*, const void*, size_t)’ writing to an object of a non-trivial type ‘std::array<std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >, 24>::value_type’ {aka …
```
=> FW: fix the memmove in background_scan_update_timestamps()

framework/sandstone.cpp
We wanted the oldest, not newest, as evidenced by the fact that `timestamp_oldest` wasn't used anywhere.
=> FW: fix which timestamp we were checking for the batch time

framework/sandstone.cpp, framework/sandstone_p.h
This is a set of simple no-op changes, just to improve the code a little
* removed (void) parameters
* passing "now" as a variable to background_scan_update_load_threshold()
* merged background_scan_update() into background_scan_wait()
* removed unnecessary init_timestamp constant variable
* removed the SandstoneBackgroundScan::timestamp_* constants
* moved the background scan's time constants to a namespace
* renamed and capitalised said constants names
=> Background scan refactor 1

framework/sandstone.cpp
We used to exit the tool with the number of tests that had failed a long time ago. We don't do this any more, because each exit code has a special meaning.
=> FW: remove the max 127 test failure limitation

framework/sandstone.cpp
Otherwise, LOG_LEVEL_QUIET isn't enough.
=> FW: move the setting of the verbosity up, before we print warnings

framework/sandstone.cpp
This PR continues the fixing and refactoring started in the previous refactor (#119)
* fix std::move of the array, which we attempted to fix but didn't do the job properly
* fix initialisation of the background scan timestamps
* add some more logging info to the background scan
* replace system_is_idle() with a function that returns the load
* move wait_delay_between_tests_with_deviation() into a lambda
* refactor the background scan's random time-waiting code
* hoist the long wait out of the loop
* don't wait too long between test starts
=> Background scan refactor (2/2)

framework/scripts/make-gitid.pl
Use the proper Perl stream name we've just opened.
Commit @ca4a226aef25527cdd76775a6154435cf9331f40 (PR #114) made the
script chdir() to the $MESON_SOURCE_ROOT dir so we could find the .hash
file properly. But that required opening the output file before the
chdir() (so we could deal with relative paths the right way), so I had
to change the name of the Perl stream from F to HASH. But I missed one
update.
Plus two minor updates to help debugging the script.
=> Meson: fix make-gitid.pl with non-Git builds

framework/sandstone.cpp
The clean up in commit @c01b34b399e3d57cedf8d85479a174b4206b7bc1 (PR
#113) moved the update of total_failures below the use of the variable.
I really need to add some unit tests to the framework. I'll do that
right after this PR.
=> FW: fix triage runs

framework/sandstone.cpp
I've removed the ones that only reset the values back to their defaults.
=> FW: update the default restricted-cmdline options

meson.build
We aren't building any python libraries, so meson's introspection step is
overkill. Just look for the python3 interpreter and be done.
=> meson: use find_program() to locate python3

framework/sandstone.cpp, framework/sandstone_p.h
This allows the tool to be restarted (for example, after an update) and
retain its average CPU consumption. There's no intention in this commit
to restart the scan wherever it was interrupted, though.
This will store the timestamp file in the runtime directory, which MUST
be specified via an environment variable. systemd does that for us if
you set the RuntimeDirectory= entry in the .service file[1]. I've chosen
the RuntimeDirectory because it's erased after boot (it's on tmpfs on
Linux).
This commit does NOT implement a race condition prevention, despite use
of atomics. If two instances of OpenDCDiag are launched with --service
and with the same runtime directory, they will step on each other's
toes. Preventing that is an exercise for the upper layer, like systemd.
This commit also does …
=> FW: implement stateful timestamps for the background scan

bats/sanity-check/20-selftests.bats
Somehow this has started failing with WINE builds:
"MZ" is the magic of a DOS executable, which Windows executables still
carry as a stub. So somehow sandstone.cpp is reading the wrong file.
=> CI: use real test files instead of redirected file descriptors

framework/sandstone.cpp
This allows more specific diagnostics to be printed at the end of the
execution.
=> FW: pass the per cpu failures to epilogue.

framework/Floats.cpp, framework/fp_vectors/Floats.h, framework/sandstone.h, framework/unit-tests/sandstone_data_tests.cpp, framework/unit-tests/sandstone_utils_tests.cpp
All #defs follows the same pattern of names (to avoid further confusion).
Remved "general NaN" from floats (to keep consistent with the definition).
Some common macros added.
Random functions kept in single place (alloc() moved a bit).
This is a part of '[rng_bits]' PR (https://github.com/opendcdiag/opendcdiag/pull/129), to keep the task tidy.
=> [Floats] Fixing #defs to keep consistent pattern over all types

framework/sandstone.h, framework/sandstone_context_dump.cpp, framework/unit-tests/sandstone_utils_tests.cpp
GCC 12 reports a false positive warning originating in system (libgcc's)
headers that some of the variables can be (or are) used uninitialized.
These variables were explicitly set to undefined values because they do
not affect the computation, but are part of the instruction.
GCC bug is tracked here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105593
=> Silencing warnings that come from <immintrin.h> for AVX512

framework/sandstone.cpp, framework/sandstone_p.h
We do new() it properly, so it's irrelevant whether it's trivially
constructible or not. Because it won't be in C++20, as std::atomic is no
longer trivially constructible either.
=> FW: only require trivial copying and destructing for SharedMemory

framework/logging.cpp, framework/sandstone_iovec.h
GCC 12 incorrectly reports reads outside boundry of an object when we
call writev with IoVec wrapper. We get warning as if it was a single
object and not an array:
../opendcdiag/framework/sandstone_iovec.h:39:18: warning: ‘ssize_t writev(int, const iovec*, int)’ reading 48 bytes from a region of size 16 [-Wstringop-overread]
39 |     return writev(fd, vec, std::size(vec));
|            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
../opendcdiag/framework/sandstone_iovec.h:16:8: note: source object ‘{anonymous}::IoVec::<anonymous>’ of size 16
16 | struct IoVec : iovec
|        ^~~~~
In file included from ../opendcdiag/framework/sandstone_p.h:24,
from ../opendcdiag/framework/sandstone.cpp:64:
/usr/include/sys/uio.h:52:16: note: in a call to function ‘ssize_t writev(int, const iovec*, int)’ declared with …
=> Silencing false positive warnings from writev

framework/sandstone.cpp, framework/sandstone.h
The _compilerCpuFeatures (from cpu_features.h) corresponds to the same
bit flags as .minimum_cpu_feature and includes all the features that the
compiler is allowed to use when generating code, according to the
-march= compiler flag.
This should help catch the majority of mistakes of forgetting to set the
CPU feature (at all or some bit). It cannot catch everything when a test
uses extra CPU features via direct assembly or via intrinsics &
__attribute__((target("xxx"))).
=> FW: record for each test the compiler-required CPU features

framework/sandstone.cpp, framework/test_selectors/WeightedNonRepeatingSelector.h, framework/test_selectors/WeightedSelectorBase.h, framework/unit-tests/WeightedTestSelector_tests.cpp
Test selection for some options like --1sec/--2min/--5min was happening
in a non-random order.  This will restore the randomness to the tests
chosen to execute when using these options.
=> Fixed random test selection issue with --1sec/2min/5min options

framework/sysdeps/unix/child_debug.cpp
In case of Position Independent Executables, the RIP alone will be
ambiguous (as OpenDCDiag is more than 4 kB of code).
Running:
```sh
for ((i = 0; i < 10; ++i)); do
echo -
./opendcdiag -Y2 -o - --selftests --retest-on-failure=0 -e selftest_sigsegv
done | yq '.[].tests[].threads[].messages[] | select(.level == "error") | .text'
```
Produces:
```json
"E> Received signal 11 (Segmentation fault) code=1 (SEGV_MAPERR), RIP = 0x55d16a03ce7f (opendcdiag+0x61e7f), CR2 = 0x7f5, trap=14 (PF), error_code = 0x4"
"E> Received signal 11 (Segmentation fault) code=1 (SEGV_MAPERR), RIP = 0x564016029e7f (opendcdiag+0x61e7f), CR2 = 0xf73, trap=14 (PF), error_code = 0x4"
"E> Received signal 11 (Segmentation fault) code=1 (SEGV_MAPERR), RIP = 0x563ab37d9e7f (opendcdiag+0x61e7f), CR2 = 0xe7d, trap=14 (PF), …
```
=> FW/Unix: print the module name and offset of the crash locus

bats/sanity-check/20-selftests.bats
ie. match name-v123-suffix (1234567890123456789012345678901234567890)
Signed-off-by: dawid-sabat <dawid.sabat@intel.com>
=> bats: regex fix to match suffixes in version string

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/selftest.cpp, framework/test_selectors/TestrunSelectorBase.h, framework/test_selectors/WeightedSelectorBase.cpp
Instead of printing an error. This allows us to be backwards-compatible with test list files that contain names we've retired. It also makes --test-file-list follow the same behaviour as -e.
Added tests for both.
=> FW: make --test-list-file ignore skip-quality tests

framework/sandstone.cpp
If OpenDCDiag was unpacked into a dir like
```
c:\OpenDCDiag-1.0\opendcdiag.exe
```
it would fail to run with the message "GetModuleFileNameA: No error" because the path was exactly 32 characters and no error had occurred (though that use of perror() is also wrong because GetModuleFileName does not set errno).
This was probably introduced during refactor, when the path was a C array, for which sizeof(path) was a correct number. sizeof(std::string) is an implementation detail, 32 bytes on 64-bit libstdc++ with the C++11 ABI.
=> FW/Win32: fix running OpenDCDiag when the path was 32 characters

framework/forkfd/forkfd_c11.h
Replace the macro use with the expansion of the macro as it appears in both libc++ as well as libstdc++.
Fixes Clang 15 C++20 warning-turned-error:
```
forkfd.c:157:39: error: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Werror,-Wdeprecated-pragma]
static ffd_atomic_int forkfd_status = FFD_ATOMIC_INIT(0);
^
forkfd_c11.h:51:37: note: expanded from macro 'FFD_ATOMIC_INIT'
#define FFD_ATOMIC_INIT(val)        ATOMIC_VAR_INIT(val)
^
/d/llvm/15/bin/../include/c++/v1/atomic:2671:43: note: macro marked 'deprecated' here
^
```
Matching Qt review: https://codereview.qt-project.org/c/qt/qtbase/+/436040
=> forkfd: fix Clang 15 ATOMIC_VAR_INIT deprecation warning

framework/sandstone.cpp, framework/sandstone_p.h
The documentation for that Win32 function[1] says:
> The global variable _pgmptr is automatically initialized to the full
> path of the executable file, and can be used to retrieve the full path
> name of an executable file.
[1] https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea
=> FW/Win32: replace the use of GetModuleFilenameA with _pgmptr

framework/sysdeps/linux/kvm.c
These were noticed during a review of the code.
- Fix a potential file descriptor leak
- Don't madivse NULL
- Reset file descriptors and memory pointers to their zero state when we recreate the VM
- Fix an indentation issue
- Add a missing error check.
=> FW: kvm: Fix a few issues with the kvm framework code

framework/forkfd/forkfd_linux.c
This architecture is not CLONE_BACKWARDS in any way.
Matching Qt review: https://codereview.qt-project.org/c/qt/qtbase/+/440005
=> forkfd/linux: add support for LoongArch

framework/logging.cpp, framework/sandstone_ssl.cpp
Openssl interface fixes.
Both commits fix the problem of framework interface using/printing info of Openssl used during build time instead of using the one available at runtime.
=> Fix openssl interface and logging

framework/sandstone.cpp
We do want to have an arena per thread that we will start, to avoid
contention in malloc() of every thread. Instead, it's much better to
simply allow each thread to have its own arena.
glibc's ptmalloc implementation creates a certain number of arenas
("M_ARENA_TEST", which defaults to 8 on 64-bit systems) before querying
the system config. Up until glibc 2.36, the query had a bug[1] that
failed to initialise some memory, so glibc concluded that the system had
lots of threads available, which albeit incorrect, was actually good for
us: OpenDCDiag sets the affinity for the worker threads to exactly 1
logical processor.
[ChangeLog][Framework] Fixed an issue encountered with glibc version
2.35.1 or later, which caused memory allocations in test threads to
contend with each other. This caused …
=> FW/Linux: set the malloc arena count to 2x the number of processors

framework/sysdeps/linux/msr.c
In case of CONFIG_X86_MSR=y, there's no "initstate", but /sys/module/msr is there. We could also just check for the /dev/cpu/NN/msr node's existence.
=> FW/Linux: don't assume the MSR driver is always a module

framework/sandstone.cpp
This reverts commit 7e034044e170ea0e698788e5adf2f5e317f749db.
Restore the default behavior of the glibc memory management. Disabling M_TRIM_THRESHOLD may have undesired side-effects on the behavior of the other memory allocation functions. E.g., the documentation states: "Dynamic adjustment of the mmap threshold is disabled if any of the M_TRIM_THRESHOLD, M_TOP_PAD, M_MMAP_THRESHOLD, or M_MMAP_MAX parameters is set."
=> Revert "FW/Linux: apply M_TRIM_THRESHOLD to the child process"

framework/sandstone.cpp
I added that in commit @131c56580d7cfcbd69f7e8f1a9cb22914ef07dde but didn't add to everything. Another case is on SIGINT, but that's ok.
=> FW: call the application footer code in case of OOM/timeout conditions too

framework/sandstone.cpp
MSDN says we have to quote arguments passed in argv if htey contain space and we don't want them to get split:
Spaces embedded in strings may cause unexpected behavior; for example,
passing _spawn the string "hi there" will result in the new process
getting two arguments, "hi" and "there". If the intent was to have the
new process open a file named "hi there", the process would fail. You
can avoid this by quoting the string: "\"hi there\"".
The lack of quoting were causing program to exit with error due to invalid argv[0] and thus program_invocation_name in child processes.
=> argv[0] is now quoted on Windows before being passed to _spawn

framework/logging.cpp
This is required for printing of progress bar correctly. Earlier we were seeing some escape sequences in the stdout (instead of being interpreted).
=> Enable interpreting of virtual terminal sequences escape sequences on Windows

framework/scripts/x86simd_generate.pl
Natural sorting of 'x86_architectures' array to keep binary images identical from compilation to compilation. CPU generations are alphanumerically sorted by features (t.i. list containing number of enabled features as '%02d' and names of these features).
Signed-off-by: Jarek Poswiata <jaroslaw.poswiata@intel.com>
=> cpu_features.h::x86_architectures sorted properly

framework/topology.cpp
We wanted to increase the vector holding the information about each CPU when we found a new CPU, so it should have been >= the current size. It was working *mostly* fine before this, so long as the Linux processor numbers didn't have any gaps, because the next number would be equal to the vector size. But it could crash the moment a gap existed because we wouldn't resize the vector.
[ChangeLog][Framework] Fixed a bug parsing /proc/cpuinfo on Linux whenever the /proc file had a gap in the processor numbering. This bug could cause the tool to crash on start, but should not cause it to report CPU failures.
=> FW/topology: fix inverted conditional in parsing /proc/cpuinfo

framework/logging.cpp, framework/meson.build, framework/sandstone_config.h.in, framework/sandstone_ssl.cpp, framework/sandstone_ssl.h
This commit fixes includes:
- Define SANDSTONE_SSL_LINKED. This macro would be use when library is linked (either dynamically or static).
- Log Openssl version only when function is not a null pointer. This could happen when library could not be loaded.
- Initialize functions when library is linked.
=> FW: Fix Openssl link process

framework/sandstone.cpp, meson.build
On Linux we are using 5 minute counter from /proc/loadavg to determine if the system was in idle state for the last 5 minutes. This patch implements similar counter but for Windows.
=> Adding system_idle_load implementation for Windows

framework/sandstone_ssl.h
Add 3 common used openssl groups of APIs:
- X509: Pubkeys certificates standard routines
- PEM: Format specific routines
- BIO: IO stream abstraction routines
=> FW: sandstone_ssl add more APIs for x509, PEM and BIO support

framework/sandstone.cpp
In case of failure in the process of reading CPU avereage load we should return the system is busy.
=> Fixing default values for average cpu load

framework/sandstone.cpp, framework/sandstone.h
This adds `test_loop_start` and `test_loop_end` symbols so one can extract the looping of a given OpenDCDiag-driven test. They complement `test_start` and `test_end`, but only work for tests that use `TEST_LOOP`.
All four functions now mark their existence by way of an expensive no-op of `CMPXCHG EAX, EAX`. The RAX register will contain the main type "TESTLOOP" or "TESTMAIN" string, and the EDX one will have the state ("STRT" or "END\0"). Both the instruction and the constants are very distinctive. Doing this was inspired on <valgrind.h>, which communicates with the Valgrind by an expensive NOP of rotating RDI left four times, adding up to 64 bits.
=> Allow instrumenting TEST_LOOP

.gitignore, bats/testenv.bash, framework/logging.cpp
This change enhances the TAP output format to match YAML format in what                                                                                                                                           
relates to the random generator state.                                                                                                                                                                            
When using TAP output format, the per-test random generator state is                                                                                                                                              
omitted hence making it difficult (and confusing) to reproduce the test …
=>    Tap format: print corresponding RNG state.

framework/selftest.cpp
log_platform_message() is not thread-safe. See #153, which is closed as "won't fix".
=> FW/selftests: don't call log_platform_message in run function

framework/logging.cpp, framework/sandstone.h
Couple of commits:
1)  Adds `format_and_print_message` function. This function adds the `print_content_single_line` and `print_content_indented` functions. All logging formats use this function to take care of newline and escaping formats. This commit will be used a prerequisite to add skip message feature.
Verified that log messages are fine:
```
threads:
- thread: main
messages:
- level: info
text: |1
I> This test requires atleast 
2 cpus to run
- level: debug
text: |1
d> This test requires atleast 
2 cpus to run
- level: warning
text: |1
W> This test requires atleast 
2 cpus to run
- { level: info, text: 'I> Init function requested skip with code -255' }
```
``` lock_in_mispredicted_branches_virtualized = no
- |
I> This test requires atleast 
2 cpus to run
- |
d> This test requires …
```
=> Logging: Add format_and_print_message function

framework/sandstone.cpp
Built-in list of tests is generated on appropriate test_list.csv. Without the initialzation some tests are not properly initialized and might fail on fatal conditions (.test_run not set, common settings from pre-initialization not applied).
=> Proper initialization of tests from built-in list.

bats/sanity-check/20-selftests.bats, bats/yamltest.py, framework/logging.cpp, framework/sandstone_utils.h, framework/selftest.cpp
The other result types were always a string, so some parsers failed to
properly extract the details here and ended up blank.
[ChangeLog][Framework] Changed how the YAML output format logs crashes
and other unexpected operating system errors. Previously, they were a
YAML object in the "results" entry, instead of the "pass" or "fail"
string. Now, those will print either "crash" or "operating system error"
for that entry, with the details moved to the "result-details" entry.
=> FW/logging: split the crash / OS error result from the result: line

framework/sysdeps/unix/child_debug.cpp
It could be useful to get glibc debug info, but that's actually easy for us to do from the post-crash backtrace information, as OpenDCDiag prints the glibc version in the header. But the Linux distribution's debug server will definitely not have information about OpenDCDiag or OpenDCDiag-based tools, so it's preferable to get a fast answer than a more detailed one.
=> FW/Unix: disable DEBUGINFO_URLS before launching gdb for backtrace

framework/sandstone_test_utils.h, framework/unit-tests/sandstone_test_utils_tests.cpp
Picker weights are 32 bit to avoid overflow when summing all weights Input weight type must now be uint32_t instead of uint64_t
=> Made WeightedPicker weights 32 bit

framework/sysdeps/unix/child_debug.cpp
Commit @9707420b45fec98152d2417a1ada1be8fc248eba added use of this variable, which on Linux/glibc is declared in <unistd.h>. But we need to explicitly declare it for FreeBSD.
=> FW/child_debug: environ needs to be explicitly declared on BSDs

framework/sandstone_ssl.h
Otherwise, we can't compile against hardened OpenSSL that Linux distributions usually ship.
=> FW: remove RC4 cipher functions from sandstone_ssl.h

framework/sysdeps/windows/win32_stdlib.h, meson.build
This is something we already did for Windows, due to a GCC limitation
in emitting the necessary SEH metadata (see[1]). This updates the
Linux and other builds to the same, by asking the assembler to
generate only unaligned instructions.
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49001
=> Remove x86 aligned vector memory-operation instructions

framework/scripts/x86simd_generate.pl
In some versions scalar %hash does not return correct hash size, but scalar keys %hash does.
=> x86simd_generate.pl: fix for older versions of perl

.github/workflows/build.yaml, tests/meson.build
We forgot to apply the `march_flags` for tests_hsw and tests_skx, which are exactly the ones where we want the -Wa,-muse-unaligned-vector-move option to go. This fixes running the eigen_svd_cdouble test on Windows after commit @442ba21b4e5fed017af80b55503282096397c271 (PR #215) removed the old workaround.
=> Fix crashes of tests_skx tests on Windows

.github/workflows/build.yaml, bats/sanity-check/20-selftests.bats, meson.build
It's probably best to build OpenDCDiag in release-like modes, so it doesn't take *too* long to run. This improves the selftests too, because some of the test functions check the timing.
To make the Wine-based run work, I needed to upgrade it, so this PR updates the Windows image to Fedora 38, which carries MinGW/GCC 12 and Wine 8.6.
=> CI: fix attempts to run OpenDCDiag after building

bats/sanity-check/20-selftests.bats, bats/yamltest.py, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone.h, framework/selftest.cpp
These changes will enable tests to add reason that whey skip a test. Skips might be due to cpu that doesn't support the test, kernel not supported, device not found etc.
Truncated output from one of the tests that will skip:
skip in main:
```
- test: lock_in_mispredicted_branches
result: skip
skip-category: RESOURCE_UNAVAILABLE
skip-reason: This test requires atl east 2 cpus to run.
```
skip in run:
```
- test: lock_in_mispredicted_branches
result: skip
skip-category: RUNTIME_SKIP
skip-reason: Skipped in Run. Check individual thread messages
```
The yaml format will escape special characters in the skip message but not new line since we are printing the skip message in a single line.
=> Skip feature: add "Skip Reason" framework changes

tests/ifs/ifs.c
Instead of stopping execution when a failure is found, keep going untill all cores have been tested. Details about the error will be saved on logs, so no need to worry about override them.
=> IFS: don't stop execution at failure

tests/ifs/ifs.c, tests/ifs/unit/ifs_unit_utils.h, tests/ifs/unit/ifs_unittests.cpp
The last two IFS PRs were incompatible with each other. Each one was fine on its own, though. Unfortunately, GitHub-based CIs are too stupid to test-on-merge and we have to apply these "fix build" commits.
=> unittests: fix build

framework/sandstone_p.h
We observed, that on Windows, when system is "doing nothing" we read cpu utilization values around 0.3 and always miss the previously used threshold of 0.2 by a little bit.
=> Windows: Background scan: Raising system idle threshold

framework/random.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/sandstone_system.h, framework/sandstone_utils.h, framework/sysdeps/unix/meson.build, framework/sysdeps/unix/resource.cpp, framework/sysdeps/unix/signals.cpp, framework/sysdeps/windows/meson.build, framework/sysdeps/windows/resource.cpp, framework/sysdeps/windows/signals.cpp
Along with other cleanups to the signal handling.
Linux defaults to 1024 file descriptors by default (a legacy caused by
FD_SETSIZE being 1024). The logging framework needs 1 file descriptor
for each thread for the logging file. If a test required two file
descriptors per thread, as in the example of creating a pipe, we were
limited to 341 processors before starting to get unexpected OS errors.
There are many 8-socket systems commercially available that exceed those
limits. An 8-socket 28-core system of the Cascade Lake generation would
add up to 448 logical processors. An 8-socket 60-core Sapphire Rapids
racks up to 960 logical processors.
This commit assumes that 4 file descriptors per thread will be enough
for all tests, plus a reasonable, baseline overhead. This means we won't
touch …
=> Fix file descriptor insufficiency on Linux

framework/unit-tests/sandstone_data_tests.cpp
GCC 13[1] and LLVM 16[2] changed their AVX512BF16 intrinsics that used to use short to using __bf16, now that they support said type, as a result of adopting P1467[3]. This caused the code in this test to insert an integer conversion that didn't use to be there. See the side-by-side comparison in
https://gcc.godbolt.org/z/K1PYMEocT
for an illustration.
We hadn't noticed this until now because we have only recently begun using GCC 13 and the CI that runs those unit tests hadn't had any Cooper Lakes or Sapphire Rapids. The developers' laptops (Ice Lakes and Tiger Lakes) don't have AVX512BF16 support.
[1] https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=87235f1e5c740de9c6f72a5dd7d7eb9cb7df2e1d
[2] https://github.com/llvm/llvm-project/commit/bc1819389fb4701cdeba5e093278e32dd668d6d5
[3] …
=> FW/Unit-tests: fix BF16 tests on BF16-capable CPUs

bats/sanity-check/20-selftests.bats
On newer Fedora systems (38), we're getting:
```
egrep: warning: egrep is obsolescent; using grep -E
```
=> CI: Replace egrep with grep -E

framework/sandstone.cpp
Framework skips a test if the CPU doesn't support the test.
=> FW: Replace log_info to log_skip in sandstone.cpp

framework/sandstone.cpp
The child process won't have OpenSSL after execve(). If we need these tests in the future, we can call sandstone_ssl_init() in the child process again.
=> FW/OpenSSL: don't init SSL in -fexec mode with dynamic loading

bats/sanity-check/20-selftests.bats, framework/logging.cpp
Replace default log level of skip from 0 to 1.
Add bats tests "TAP silent output" and "YAML silent output".
Initial issue case:
```
$ ./opendcdiag -e ifs
command-line: 'opendcdiag -e ifs'
version: opendcdiag-0910b3027a62-dirty
.  skip-reason: 'could not find IFS control files in intel_ifs_0: either IFS is not supported on this system or this kernel does not support IFS (No such file or directory)'
threads:
- thread: main
messages:
exit: pass
$ ./opendcdiag -e ifs --quiet
command-line: 'opendcdiag -e ifs --quiet'
version: opendcdiag-0910b3027a62-dirty
.  skip-reason: 'could not find IFS control files in intel_ifs_0: either IFS is not supported on this system or this kernel does not support IFS (No such file or directory)'
threads:
- thread: main
messages:
exit: pass
```
After the fix
```
$ …
```
=> FW/Logging: Fix skip reasons quiet mode issue

bats/sanity-check/20-selftests.bats
The regular expression was too inflexible, preventing things like "pr242". The release process becomes responsible for ensuring the version matches the tool's desired version number.
=> CI/Bats: allow free-form version numbers in the sanity-check

tests/ifs/ifs.c
Unless all threads return "EXIT_SKIP", the test won't be marked as "SKIP". This is the case for thread 0, which almost always returns "EXIT_SUCCESS", causing false positive reports.
To fix this, a control variable has been added to keep track if at least one "EXIT_SUCCESS" occurred, otherwise test will be marked as "SKIP".
=> IFS: Fix false positive report when all threads skips.

tests/meson.build
Commit 18d65217eedddbaee3372012a7a282929035845c accidentally reversed the effects of commit a9e1a75117e4516783d1d96e5b3e4ff52354f130, causing the code generation for eigen_svd_cdouble to change meaningfully. This commit brings the code generation back to what it was, by overriding march_flags' -mtune with another -mtune.
=> Meson: Add extra -mtune to AVX512 to override march_flags' -mtune to restore code generation.

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/selftest.cpp
memcmp_or_fail() was introduced to allow easy checking that a given data set was correct, reporting it in a standard format in case it isn't (that includes virtual and physical addresses, in case they are important for debugging). It includes an memcmp(), so we don't call into the framework unless a difference was found. Because memcmp_or_fail() is inline, the compiler often inlines memcmp() itself, replacing what would be a function call into libc with a simpler version.
Interestingly, the mere act of memcmp()ing two data blocks sometimes triggers a Silent Data Error. Therefore, we can't be assured that memcmp() and memcmp_offset() will agree. This commit removes the assertion that memcmp_offset() is able to find a difference and introduces proper reporting.
```yaml
messages:
- level: …
```
=> FW/logging: allow for memcmp_offset() failing to find a difference

framework/meson.build, framework/sandstone.h, framework/sandstone_context_dump.cpp, framework/sysdeps/unix/signals.cpp, framework/test_knobs.cpp, meson.build, tests/meson.build
This fixes:
* Annoying Clang warnings about use of GCC-specific warning names
* Compiling and linking to dependencies, that we forgot to tell Meson were dependencies
* Missing #includes for FreeBSD's C library (`setsid`)
* Missing #includes for LLVM libc++ (`std::vector`)
=> FreeBSD and Clang fixes

framework/sandstone.cpp, framework/sandstone.h, framework/selftest.cpp, tests/ifs/ifs.c, tests/ifs/sandstone_ifs.h, tests/ifs/unit/ifs_unittests.cpp, tests/mce_check/mce_check.cpp
Not all tests need to run in parallel. In fact, some of them can't run in parallel (the Intel In-Field Scan ones, for example, due to limitation of the kernel API), so they were marked as sequential.
The `mce_test` test is another case.
=> FW: introduce test_schedule_sequential to run threads sequentially

framework/sandstone_p.h
"Fix" as in "make fixed". It wasn't wrong.
=> FW: fix current_fork_mode() for Windows under RestrictedCommandLine

framework/sandstone.cpp
-1 was definitely wrong: that included the bit for FFD_NONBLOCK, which caused the runs that crashed to also crash the parent process with:
```yaml
tests:
- test: selftest_sigsegv_instruction
details: { quality: beta, description: "Crashes with SIGSEGV (instruction)" }
state: { seed: 'LCG:1980176068', iteration: 0, retry: false }
time-at-start: { elapsed:      0.000, now: !!timestamp '2023-06-23T00:09:07Z' }
forkfd_wait: Resource temporarily unavailable
```
Because we went directly from the child debug file descriptor to forkfd_wait().
=> FW/FreeBSD: fix flags passed to forkfd()

framework/sysdeps/unix/child_debug.cpp
We ended up not using their TIDs.
=> FW/child_debug: remove unused FreeBSD and macOS functions

framework/sysdeps/unix/child_debug.cpp
It hasn't printed the smaps for ages.
=> FW/child_debug: remove deprecated "--on-hang=smaps" option

bats/sanity-check/20-selftests.bats, framework/sysdeps/unix/child_debug.cpp
It was a portion of "backtrace", but we may want to get the context only without incurring the cost of launching gdb.
=> FW/child_debug: add --on-crash=context to dump only the context

.github/workflows/build.yaml, framework/sandstone_data.h, framework/selftest.cpp, framework/sysdeps/linux/effective_cpu_freq.hpp
* Hardcode the limit values for `_Float128`, because Clang doesn't define the `__FLT128_xxx__` macros
* Fix build: it only has `__rdtscp`, not `_rdtscp`
* Disable 16-bit KVM tests with Clang, because it can't do `.code16` properly
Finally, I enabled it in the CI (build only).
=> More clang fixes

framework/sandstone_p.h
SANDSTONE_NO_LOGGING is defined if and only if the default output format is already "no_output" (-Dlogging_format=none).
=> FW/logging: remove unnecessary #if for DefaultOutputFormat

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/selftest.cpp
The slicing feature was added back on 2019-10-23, with the documentation:
>  "Maximum number of threads to assign to the given test. This might be useful when the test does not scale well for a very big number of cores. 0 (default) means use all available. Any other value will make the test_run() function to be called only for a subset of the overall available threads, not all of thread_count. The framework will try to spread out package/core usage as much as it can, when this mode is activated"
At that time, that was really just a limit of the number of threads: all logical processors above that limit simply weren't tested. The sliding window functionality was added on 2019-11-05.
The motivation for the feature is sound and still relevant: there are tests that don't scale well, for …
=> FW: remove the test sliding-slice feature

framework/logging.cpp, framework/sandstone_p.h
log_data() is probably only used by tests, so there's no race problem there. But log_message() may be used on the main thread's messaging, which could cause a race condition.
=> FW/logging: use atomics for the message count and data size

framework/sandstone.cpp, framework/sandstone_p.h
I added this back in February 2021 to support running with secure enclaves, where each process gets its own memory encryption and thus can't share memory with other processes. It was later used for the early Windows port, before we discovered how to have the child process inherit file descriptors from the parent (you have to use [`_spawnv()`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/spawnv-wspawnv), not directly [`CreateProcessW()`](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw)), but isn't needed any more there.
Given the upcoming changes to support multiple child processes, this would be a complexity I could live without, so I'm removing. If the need arises, we can bring it back later, adapting as …
=> FW: Remove the ability to run without shared memory

bats/sanity-check/20-selftests.bats, framework/random.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/selftest.cpp
Instead of doing it serially before the child is even started. That removes them from the critical path. It wasn't a lot of time, but it's a nice benefit, especially when you have 960 logical processors (8 sockets of 60 hyperthreaded cores).
This additionally makes it so each thread has a generator state that doesn't depend on how many threads started before it. Previously, if you decided to skip some logical processors in re-testing, the ones you did test wouldn't get the same sequence.
=> FW/random: move the thread's seeding into the thread itself

framework/sysdeps/unix/child_debug.cpp
For the case of the context transfer, we don't need to wait, so let the child simply proceed.
=> FW/child_debug: only hold the child back if we're attaching GDB

framework/sandstone.cpp
It's already been called by the parent.
=> FW/SharedMemory: don't call the constructor in the child process

framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_iovec.h, framework/sandstone_p.h, framework/sandstone_utils.h
This removes the `--use-predictable-file-names` option (undocumented, only available in debug builds) and the associated predictable file name support. This was added during the port to Windows, when we thought that we'd need to have predictable file names so the child process would be able to reopen the files. But it turns out that Windows and the C runtime can let child processes inherit file descriptors.
Then it adds `writevec()`, which does the same as the existing `writeln()` but without a newline (so the latter is reimplemented in terms of the former), then proceeds to using it in framework/logging.cpp.
The actual removal of `FILE *` support will be in another PR. It depends on changes to child_debug.cpp (see #252, #274, #275, etc.)
=> FW/Logging: clean ups in preparation for removing FILE*

framework/meson.build, framework/sandstone.cpp, framework/topology.h, framework/unit-tests/topology_tests.cpp
The -n option isn't documented for end users, but we use it a lot. Let's ensure we mask off the unused CPUs from the ambient CPU set, lest we accidentally use them.
This also adds `Topology::limit_to()` with its unit tests and some code updates.
=> FW/Topology: apply the -n value to the enabled_cpus

framework/sandstone.cpp, framework/sandstone_p.h
This replaces the direct access to [`_pgmptr`.](https://learn.microsoft.com/en-us/cpp/c-runtime-library/pgmptr-wpgmptr) with [`_get_pgmptr`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/get-pgmptr).
It also removes the access to `sys_nerr` and `sys_errlist` because those are likewise not declared with UCRT. I'm not bothering with a replacement because this code was removed by PR #272 (commit 6526b2af82900a3545482e41713938b35388bb90) in the `socket-separation` branch.
=> FW/Win32: Fix build with UCRT

framework/sandstone_p.h
I had a neater solution but that ran afoul of C++ not allowing me to do what I wanted. It was
```c++
union SandstoneApplicationStorage
{
SandstoneApplication app;
unsigned char dummy[sizeof(app)];
constexpr SandstoneApplicationStorage() : dummy{}
{}
constexpr ~SandstoneApplicationStorage()
{}
};
constinit inline SandstoneApplicationStorage _sApp;
#define sApp    (&_sApp.app)
```
This failed to compile with Clang saying this destructor can't be `constexpr` and GCC adds load-time code to register the destructor (meaning it ignored the keyword but didn't allow it to be `constexpr`).
=> FW: mark _sApp() noexcept

framework/sandstone.cpp, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp
Instead of having the parent remember what the child's PID is. This allows grandchild processes to crash and still get debugged.
This is incomplete: if more than one child crashes at the same time,
they will all be stopped on read() at
```c++
// now wait for the parent process to be done with us
char c;
IGNORE_RETVAL(read(crashsocket, &c, sizeof(c)));
```
It's unspecified which one we wake up when write()ing back to them. The next commit will fix that.
=> FW/child_debug: let the child inform its PID to the parent

framework/sandstone_p.h, framework/sysdeps/darwin/futex.h, framework/sysdeps/freebsd/futex.h, framework/sysdeps/generic/futex.h, framework/sysdeps/linux/futex.h, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/windows/futex.h
I decided to use the thread_state variable in the main thread for this. It's currently unused: instead of setting it to the result of the init() function, we return that state in the process's exit status. But even if it were in use, this state variable can be used, because either the crash happened *in* the init() or cleanup() function or init() returned success.
I needed to enlarge this variable to 32 bits to be able to use it in a futex.
=> FW/child_debug: use futexes to make the child wait for gdb

framework/meson.build, framework/sysdeps/darwin/meson.build, framework/sysdeps/freebsd/meson.build, framework/sysdeps/linux/extract-malloc.sh, framework/sysdeps/linux/malloc.cpp, framework/sysdeps/linux/meson.build, framework/sysdeps/unix/meson.build, framework/sysdeps/windows/meson.build
This simplifies the build process and incidentally also fixes the inconsistency in build flags -- the files from sysdeps/ weren't getting the `march_flags`, for example.
Those `-DLINUX` and `-D__linux__` flags were there since the Meson build system was added to the internal repository prior to open-sourcing, but they don't seem to have a purpose because a) nothing uses the `LINUX` macro and b) the compiler predefines the `__linux__` macro for us.
To do this, I needed to rework the processing of libc.a's malloc.o so it wouldn't depend on having compiled our malloc.cpp. Because of Meson is incapable of using backslashes in custom_target() commands (see bug mesonbuild/meson#1564), I had to write a shell script to execute sed, so I decided to move the ar x command there too.
Drive-by …
=> Meson: Fix sysdeps build flags by reorganising the flags

framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp
We already opened the `FILE *` in unbuffered mode, so the stdio content was only overhead we didn't need. The few places where we still used it were removed in PR #278. By using only low-level file descriptors, we can store the file descriptor directly in the shared memory segment, reducing the size of that `ExecState` that is passed to the child process (and also removing one more hardcoded `MAX_THREADS`).
The other commits are clean-ups.
=> FW/logging: remove use of FILE* the child logging

framework/sandstone.cpp, framework/sandstone_p.h
It can be calculated from the CPU mask. It's work that doesn't need to be re-done, but this change will come in handy in the future.
=> FW/SharedMemory: don't pass thread_count in the ExecState to the child

framework/logging.cpp
Nothing uses it after the constructor.
=> FW/Logging: remove member AbstractLogger::sc (skip count)

bats/sanity-check/20-selftests.bats, framework/logging.cpp
This code was originally written in C, which is why it manipulates two raw pointers. The last version of the logging_print_results() function in C (dated 2020-07-30) still received that `const char *extra` as a parameter.
So it's high time to clean it up and remove some of the fragility. For example, if the `ChildExitStatus::extra` value isn't 0, this code was assuming the result was a crash of some sort, which made me go down the wrong path of debugging to find out why the selftest_pass test was crashing... it wasn't, the log was wrong.
Last C version:
```c
bool logging_print_results(int pc, int tc, struct test *test, const char *extra)
{
bool failed = (pc >= 0 && (unsigned)pc != (unsigned)thread_count);
const char *qual = quality_string(test);
if (qual[0] == '\0' && extra[0] != '\0') …
```
=> FW/Logging: refactor TapFormatLogger::print() to better use C++

tests/ifs/ifs.c
Rename array_bist test to ifs_array_bist. This change makes easier to group or associate it with ifs.
=> IFS: rename array_bist to ifs_array_bist

framework/sandstone_p.h
`current_test_duration` was used in the sliding-window slicing code, which was removed in 8f59e10b04ad82724d3bf2975d827f0aeb1ca022 (PR #271).
The other variables don't appear to ever have been needed in the child.
=> FW/SharedMemory: don't pass state variables to the child that the child doesn't need

framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp, framework/topology.cpp
Instead of doing a simple `memset()` in the parent process, move that to the child process and use dedicated functions to do so. This is slightly worse for now, exactly because it's not a `memset()`: that can do 32, 64, or even 128 bytes per cycle. However, once we have multiple children and the work is divided between them, this work will become parallel.
I've also split the main thread's (to become main threads') data structure from the test threads' data structure, so we can have different fields there. An upcoming field will be the test thread data's offset in the shared memory segment.
=> FW/SharedMemory: refactor the per-thread shared memory structures and their initialisation

framework/sysdeps/unix/child_debug.cpp
We still use ATOMIC_VAR_INIT in C (tmpfile.c, forkfd.c), but in C++ it's deprecated. Found by Clang/libc++:
```
child_debug.cpp:207:48: warning: macro 'ATOMIC_FLAG_INIT' has been marked as deprecated [-Wdeprecated-pragma]
```
=> FW/child_debug: stop using ATOMIC_FLAG_INIT in C++

framework/sandstone.cpp
Found by Clang 14 on FreeBSD:
```
framework/sandstone.cpp:647:67: warning: format specifies type 'unsigned long' but the argument has type 'long long' [-Wformat]
```
Indeed C++ <chrono> duration types use signed integers, because you can represent negative durations.
=> FW: fix warning about signed/unsigned mismatch in printf-style

framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h
This is a massive search-and-replace change with no actual behaviour difference for most of the application. The only actual changes are in the `spawn_child()` and `exec_mode_run()` functions, which must now communicate to each other the file descriptor to the shared memory segment instead of that temporary state file.
This makes the shared memory segment both input and output to the child process.
=> FW/SharedMemory: move SApp::ExecState's contents to SharedMemory

framework/sandstone_system.h
Makes generic code in sandstone.cpp simpler.
=> FW/Win32: declare dummy versions of the signal-catching functions

framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h
The enum was only used in the C++ side, so I changed it to an `enum class` to ensure there wasn't an accidental cast to/from integers (which there was). Therefore, I introduced an explicit mapping between those, avoiding unnecessarily clever math. Good compilers are perfectly capable of noticing when your switch labels make no transformation or identical ones for some case labels (see [1]).
Then I re-ordered the entries by severity, with the most severe ones having higher values. When we have multiple child processes, the test's condition will be the one with highest severity:
* anything beats a Skip
* any failure beats a Pass
* any crash causes the failed test to be reported as a crash
* core dumps deserve more attention than crashes that don't dump core
* OOM and OS error conditions …
=> FW: make TestResult an enum class and sort according to severity

framework/sandstone.h, framework/topology.cpp
This is optimised for little-endian CPUs: place the least-significant fields first. This way, the compiler could treat these four 32-bit fields as a single 128-bit integer, provided they were all unsigned. Since they aren't, we help it by making it so.
That means we sort -1 last instead of first, but hopefully there isn't a VM that provides this bad topology data (the tool won't be very effective inside it anyway!).
With GCC, we now generate for the comparison:
```asm
movq    24(%rsi), %rdx
movq    24(%rdi), %rcx
cmpq    %rdx, %rcx
setb    %al
je      .L5
ret
.L5:
movq    16(%rsi), %rdx
movq    16(%rdi), %rcx
cmpq    %rdx, %rcx
setb    %al
setne   %dl
andl    %edx, %eax
ret
```
Similar for Clang, only without a branch:
```asm
movq    16(%rdi), %rax
movq    24(%rdi), %rcx
xorl    %edx, …
```
=> FW/Topology: improve sorting algorithm by sorting the fields

framework/sandstone.cpp
By using a variable-length array, we can avoid the fixed-size one. One more `MAX_THREADS` bites the dust.
=> FW: replace MAX_THREADS with a VLA in run_threads_in_parallel()

bats/sanity-check/20-selftests.bats, bats/testenv.bash
There were a number of dependencies on GNUisms, like:
* missing `;` inside a sed sub-expression
* GNU grep's `--perl-regexp` support (replaced grep with Python instead, which we require anyway)
Plus fixed a mismatch between what FreeBSD's `uname -m` reports compared to elfutils' `eu-readelf`, and stopped hardcoding signal numbers (FreeBSD's `SIGBUS` is 10 on x86-64, not 7, like Linux on SPARC, MIPS, Alpha and PA-RISC).
And when running on Windows, do set `is_windows=true`.
=> CI/bats: make bats run with non-Linux systems

tests/meson.build
Looks like our Eigen SVD cdouble builds are so big that they are too big for the PE COFF file format, even with `-Wa,-mbig-obj`.
```
as.exe: tests/libtests_base.a.p/eigen_svd_svd_cdouble_noavx512.cpp.obj: section .pdata$_ZN5Eigen8internal31generic_dense_assignment_kernelINS0_9evaluatorINS_6MatrixISt7complexIdELin1ELin1ELi0ELin1ELin1EEEEENS2_INS_9TransposeIKNS8_IKNS_5BlockINS_12CwiseUnaryOpINS0_19scalar_conjugate_opIS5_EEKS6_EELin1ELin1ELb0EEEEEEEEENS0_9assign_opIS5_S5_EELi0EE11assignCoeffExx: string table overflow at offset 10000017
C:\msys\tmp\ccT4M7r1.s: Assembler messages:
C:\msys\tmp\ccT4M7r1.s: Fatal error: tests/libtests_base.a.p/eigen_svd_svd_cdouble_noavx512.cpp.obj: file too big
```
=> Meson: force -Og on Windows on debug builds

framework/sandstone.cpp
We don't pass the full path to it, so we need the "p" version to do a PATH search for us.
=> FW/Win32: use spawnvp to find gdbserver

framework/sandstone.cpp
It was only used in a single place.
=> FW: remove calculate_runtime()

framework/sandstone.cpp
Now `calculate_wallclock_deadline()` is only used in two places relating to test times and tests cannot run forever. I don't think this code was in use.
=> FW: remove duration_is_forever()

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp
We were silently accepting the option and not acting on it.
=> FW: error out early if -O is given while in -fexec mode

bats/sanity-check/20-selftests.bats
Remove the -vvv option that was causing a print of the inner loop count as the first message, instead of the data
```yaml
messages:
- { level: info, text: 'I> inner loop count for thread 0 = 0' }
- level: info
text: 'same'
data:
30 31 32 33  34 35 36 37  38 39 30 31  32 33 34 35   36 37 38 39  30 31 32 33  34 35 36 37  38 39 30 31
32 33 34 35  36 37 38 39  30 31 32 33  34 35 36 37   38 39 30 31  32 33 34 35  36 37 38 39  30 31 32 33
34 35 36
```
=> CI/Bats: fix selftest_logdata test on Linux with -fexec

framework/topology.cpp, framework/topology.h
This removes the need to keep a generation counter.
=> FW/Topology: build topology early, in load_cpu_info()

framework/sandstone_p.h
This reverts commit d31aafaf04b11a30777df2c371e30daa827cbef1. That was wrong because the exec-mode runs have two states: parent and child.
=> Revert "FW: fix current_fork_mode() for Windows under RestrictedCommandLine"

framework/sandstone.cpp, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp
All the infrastructure was there, missing only:
* placing the file descriptors in the shared memory segment
* getting the size of the XSAVE are in the child side
=> FW/child_debug: context-dumping and backtrace work with -f exec mode too

framework/logging.cpp, framework/sandstone.cpp
Lots of changes to apply "Don't Repeat Yourself" and simplify execution, plus at the end make `logging_print_results()` return the full results
Up until this point, it only returned Skipped, Passed, or Failed. Now it will return the full status, with the near-term objective of making it summarise the result from multiple child processes.
This in turn means `run_one_test_once()` can return extended results to run_one_test(). The latter will not, because at the end of the failure analysis it sets to a single condition:
```c++
/* now we process retries */
if (fail_count > 0) {
...
analyze_test_failures(*tc, test, fail_count, iterations, per_cpu_fails);
state = TestResult::Failed;
}
```
=> FW/Logging: simple refactor and clean-up

bats/sanity-check/20-selftests.bats, framework/sysdeps/unix/child_debug.cpp
This option was introduced so we could get a crash context without gdb, but we still printed:
```
--on-crash=context requires gdb but we couldn't find it.
```
I developed this functionality in the socket-separation branch, probably after commit 704f1415097aacb73d33b74f56b6f4ea74084e1d which changed the enum. So this commit backports that change too.
=> FW/child_debug: fix --on-crash=context without gdb

docs/writing_tests.md
The reference is valid until commit 441b845185937d9abf439f1391d5302b860e4b96, this commit changes the reference to point to
`framework/sandstone_test_groups.h` instead, turning the reference link valid again.
=> docs/writing_tests.md fix reference to sandstone_test_groups.h

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/sandstone_p.h, framework/topology.cpp
This is needed because we need our internal threads to be grouped together and we definitely want to run the same child on both logical processors. This does not affect Windows or FreeBSD, because those already sorted the logical processors this way, and it's how the ACPI numbering worked. Raymond Chen even had a [blog post](https://devblogs.microsoft.com/oldnewthing/20230620-00/?p=108358) about this a couple of weeks ago.
[ChangeLog][Framework] The sorting order for logical processors on Linux has changed. Previously, the tool kept the order provided by the OS, but now it will group all cores together, side-by-side. This change is noticeable when the framework prints warnings and errors from the tests: users who may be parsing the output of the tool must be aware that "thread 1" is …
=> FW/Topology: deprecate the --schedule-by option and enforce it

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_chrono.cpp, framework/sandstone_chrono.h, framework/sandstone_p.h
We don't need to store an `int64_t` nanoseconds (± 292 years of range). The range of a plain 32-bit int in milliseconds is enough (± 24.85 days).
=> FW: introduce ShortDuration to store user-configurable times

framework/sandstone.cpp
This code is running in the main thread and allocates less than a page, so it is served from the main thread's heap. That means this doesn't affect the stacks or heaps of any of the test threads, nor will it affect memory allocated by the tests' init() functions as that is also run in a separate thread since 4248649b550477eb299efcdbfd35be85bbb11657.
See #333 for a better solution for stacks.
=> FW: remove the useless code allocating random memory in run_one_test()

framework/meson.build, tests/meson.build
```
framework/meson.build:105: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.2.0': int operations with non-int. It is not commutative and only worked because of leaky Python abstractions.
Configuring sandstone_config.h using configuration
tests/meson.build:106: WARNING: Keyword argument "dependencies" defined multiple times.
WARNING: This will be an error in future Meson releases.
tests/meson.build:161: WARNING: Keyword argument "dependencies" defined multiple times.
WARNING: This will be an error in future Meson releases.
tests/meson.build:49: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.2.0': int operations with non-int. It is not commutative and only worked because of leaky Python abstractions.
```
=> Meson: fixes for warnings found in v1.2.0

framework/sysdeps/linux/msr.c
We can't gain privileges, so the result won't change if we keep trying.
Not retrying means we avoid system calls. It's not a lot, but at 2xNPROC system calls on start, even 0.5µs accumulates. This patch saves 2 ms in start up time.
Before:
```
selftest_pass_low_quality
0.122776 +- 0.000110 seconds time elapsed  ( +-  0.09% )
selftest_pass
0.182380 +- 0.000142 seconds time elapsed  ( +-  0.08% )
```
After:
```
selftest_pass_low_quality
0.1204033 +- 0.0000948 seconds time elapsed  ( +-  0.08% )
selftest_pass
0.1804157 +- 0.0000790 seconds time elapsed  ( +-  0.04% )
```
=> FW/Linux: don't keep trying to open the /dev/ MSR nodes if we get EACCES

framework/interrupt_monitor.hpp, framework/sandstone.cpp, framework/sandstone_p.h, tests/smi_count/smi_count.cpp
First, we make `count_smi_events()` return std::optional, so we don't keep trying to get the count after we've already failed once. This won't make much of a difference, with #329 applied.
Second, we replace `std::map` with `std::vector`, which simplifies code. This improves the test runtime of a single, selftest_pass run by 4 ms.
=> FW/InterruptMonitor: improve counting of SMI events

framework/sysdeps/freebsd/cpu_affinity.cpp, framework/sysdeps/linux/cpu_affinity.cpp
The two OSes have very similar API, so keep the implementation in one place. I even wrote wrapper functions, but it turns out they weren't needed because the FreeBSD libc provides the wrappers for us, including translating the ERANGE error of "insufficient buffer" for `cpuset_getaffinity()` to Linux's EINVAL for `sched_getaffinity()`.
https://github.com/freebsd/freebsd-src/blob/main/lib/libc/gen/sched_getaffinity.c
https://github.com/freebsd/freebsd-src/blob/main/lib/libc/gen/sched_setaffinity.c
=> FW/FreeBSD: delegate the common cpu_affinity.cpp to the Linux version

framework/sandstone.cpp, tests/mce_check/mce_check.cpp
This removes the parsing of /proc/interrupts on Linux between each test and when the "mce_check" test is run. In any case, the product of those checks was only comments, not properly structured data (because we introduced them for the TAP output format, before we had YAML), which means many tools never caught or stored them at all. Though as a consequence the test running in a child process, its update of the counts won't be committed, so when the test is run again, it'll compare against the original numbers from the tool's start.
The problem with /proc/interrupts is that it increases in size linearly with the number of cores.
This improves start-up time a bit if `--disable=mce_check` is passed. For `perf stat -r500 $objdir/opendcdiag --disable=mce_check --selftests -o - -e …
=> FW: move the between-test checks on MCE and thermal events to mce_check

tests/ifs/ifs.c
```
ifs.c:121:13: warning: unused variable ‘n’ [-Wunused-variable]
121 |         int n = snprintf(sys_path, PATH_MAX, PATH_SYS_IFS_BASE "%s", ifs_info->sys_dir);
|             ^
```
=> ifs: silence GCC warning about unused variable in release mode

bats/sanity-check/20-selftests.bats, framework/logging.cpp
Instead of closing and recreating more memfds, we truncate them back to zero and seek to the beginning. Unproven, but it feels like this should be faster: it's the same number of system calls between tests, but truncating and seeking can't be as expensive as a single new file- opening.
=> FW/Logging: keep the file descriptors open across tests

framework/simd.conf
New instruction sets in the 049 release:
* avxvnniint16, for Arrow Lake S (ARL-S) and Lunar Lake (LNL)
* sha512, ditto
* sm3 and sm4, ditto
* pbndkb, for Lunar Lake (LNL)
Updated instruction sets in this release:
* amx-complex, to Granite Rapids-D (so marked optional for GNR)
* enqcmd, added to Sierra Forest and Grand Ridge
* serialize, ditto
* avxvnni, ditto
* pks, added to Alder Lake (ADL)
* lam, added to SRF, GRR, ARL and LNL
* cmpccxadd, added to Arrow Lake (ARL) and Lunar Lake (LNL)
* avxifma, ditto
* avxneconvert, ditto
* avxvnniint8, ditto
Like the sha, aes and pclmulqdq instructions before, I'm leaving the SHA512 and SM3/SM4 extensions as optional. I've left `enqcmd` optional for Sapphire Rapids, Sierra Forest and Grand Ridge, since that instruction is used to communicating with …
=> simd.conf: update to Instruction Extensions manual release 049, AVX10 and APX

bats/sanity-check/20-selftests.bats
It's not that don't crash, it's that ASan prints more stuff that we don't want. Found by the internal CI running ASan:
```
not ok 7 TAP output crash
```
=> CI/Bats: don't run the crashing test with ASan

framework/sandstone.cpp
Because then we may run on an OS logical processor whose number is greater than the number of threads we're running on (e.g., --cpuset=1 will trigger this). This also fixes the reporting in `smi_count_run()`, which expected the array to be indexed by the internal thread number.
Found by ASan in the internal CI (which runs ASan as root on bare hardware):
```
==67==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000000970 at pc 0x55de9aa88dbe bp 0x7fffce5b6080 sp 0x7fffce5b6078
WRITE of size 8 at 0x603000000970 thread T0
#0 0x55de9aa88dbd in initialize_smi_counts ../opendcdiag/framework/sandstone.cpp:825
#1 0x55de9aa88dbd in main ../opendcdiag/framework/sandstone.cpp:3704
#2 0x7f745a5a7b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: …
```
=> FW: fix initialize_smi_counts() when not running over the full system

framework/sysdeps/windows/aligned_alloc.cpp, framework/sysdeps/windows/meson.build
The ones in libstdc++ do call `malloc` and `aligned_alloc` and other suitable functions we do provide. However, on Windows, that only works if you link statically to libstdc++.a. If you're using libstdc++6.dll, the already-linked DLL will instead go to the runtime (either MSVCRT or UCRT), bypassing our allocating and zeroing functions.
All the functions in this file are the same because we never throw and never return null pointers.
=> FW/Win32: Provide C++ operators new and delete

framework/meson.build, framework/sandstone.cpp, framework/sandstone_p.h, framework/sandstone_thread.cpp, framework/sandstone_thread.h, framework/sysdeps/darwin/gettid.h, framework/sysdeps/freebsd/gettid.h, framework/sysdeps/linux/gettid.h, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/windows/gettid.h
There are two reasons for this. First, it will allow us to randomise the stack addresses according to the fracture, replacing the code that was in `run_one_test()` and didn't do anything. Second, because it shows a performance improvement:
|  # Threads   | Before (µs)  |  After (µs)  |
|-------------:|-------------:|-------------:|
|            1 |        35950 |        33363 |
|           24 |        53527 |        53386 |
|           48 |        57227 |        55624 |
|           96 |        62519 |        59104 |
|          192 |        74021 |        67249 |
Subtracting the first line from all others:
<table>
<thead>
<tr>
<th rowspan=2># Threads</th>
<th colspan=2>Before (µs)</th>
<th colspan=2>After (µs)</th>
</tr>
<tr>
<th>Total</th>
<th>Per thread</th>
<th>Total</th>
<th>Per …
=> FW: pre-allocate the stacks' threads

framework/sandstone.cpp
Otherwise you can't pass -n1 for a 1-thread system.
=> FW: allow min == max in ParseIntArgument

framework/sandstone.cpp, framework/sandstone_p.h, framework/topology.cpp
This moves the `cpu_info` array into the shared memory segment as a dynamically-sized C99 Flexible Array Member. That way, the children processes (in exec mode) won't have to re-inspect the system again to find the topology.
In order to insert it, we moved the per-thread data to a dynamic offset in the segment, aligned to a page. This layout will change again, once we support multiple main threads. But the advantage of making it dynamic is that we don't have to depend on `MAX_THREADS` any more, thereby we remove the second-to-last instance of this use (see #317 for the last).
This moves the `enabled_cpus` bitset off the shared memory segment, as we don't need it any more.
=> FW/SharedMemory: remove hardcoded limit on MAX_THREADS

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp
This allows us to avoid a system call per thread, per test. However fast those system calls are (and they are fast on Linux), they add up. Here's a benchmark of the runtime of 1000 x selftest_skip in microseconds, divided by the number of threads that would have been started, with the cost of 1 of them subtracted:
| # threads  |   Before   |   After    |
| ---------: | ---------: | ---------: |
|         24 |       1.92 |       0.65 |
|         48 |       1.60 |       0.62 |
|         96 |       1.50 |       0.98 |
|        192 |       1.48 |       0.70 |
That would seem to indicate the cost of this system call is between 0.5 and 1.2 µs. The gain on Windows may be considerably bigger.
This can also be seen with selftest_pass under the same conditions, though the cost of starting the …
=> FW/Logging: check the message counter before fstat()ing the log file

framework/sandstone.h
This is in addition to `test_schedule_sequential` (added in commit c0d75bffbef27873e7afb4a229ba97ad2faa3558):
* `test_schedule_fullsystem`: equivalent to today's functionality, whereby the framework makes no scheduling decisions and simply gives the entirety of the system under test(*) to the test functions
* `test_schedule_isolate_socket`: makes a simple decision to split the system under test into its component socket processors (a "package") and run one child process per socket
All three options are optional and may not be combined with each other. If none of them are specified -- the default -- the framework will make its own decision (which I'm calling "heuristic mode"). The details of such scheduling are coming in a pull request soon.
This commit does not actually implement …
=> FW: add two values for struct test::flags to specify the test's scheduling

framework/sandstone_context_dump.cpp
There was a bad copy & paste job in the offset for two of the three components of the state.
In addition, it looks like the two components of the ZMM state can be independently set. I didn't know that was possible, but I am seeing on my Tiger Lake laptop, with the `xsave_bv` field in the XSAVE header set to 0x2a7. That means it has the entire state my system supports except for:
```c++
XSave_Zmm_Hi256    = 0x0040,            // AVX512: high 256 bits of ZMM0-15
```
```
$ cpuid -1l0xd -s0
CPU:
XSAVE features (0xd/0):
XCR0 valid bit field mask               = 0x00000000000002e7
```
What's probably happening is that the VZEROUPPER instruction zeroes the upper 384 bits of the ZMM0-15 registers and moves the Zmm_Hi256 component back to INIT state, but leaves Ymm_Hi128 (the original AVX2 …
=> FW/ContextDump: fix printing of the AVX512 state

framework/amx_common.h, framework/selftest.cpp, framework/sysdeps/unix/child_debug.cpp
On Linux, the AMX state is not saved to the stack if it is in INIT state, so as to avoid possibly overflowing user-provided stacks with the size of the AMX tiles. This meant the kernel saved much less than `xsave_size` to the stack.
This has been a latent problem, but only became visible after we changed the tests' stacks in commit 81914bdde76fe75006f8354c58083fe3848c5abd (PR #333):
```
sendmsg(4, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=..., iov_len=11008}], msg_iovlen=3, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 EFAULT (Bad address)
```
Up until last week, I'd have implemented by simply getting the highest bit in the XSTATE_BV and asking for its offset and size. That is now incorrect, after the APX specification[1] was published, because APX is feature number 19 but is …
=> FW/child_debug/Linux: fix transferring the context without AMX

framework/sandstone_p.h
```
sandstone_p.h:557:12: error: no matching conversion for functional-style cast from '(lambda at ../framework/ sandstone.cpp:913:30)' to 'Scope'
```
=> FW: fix build with Clang

framework/logging.cpp
It should be printed to stdout when either the verbosity level is high enough (level 1 for this feature) or when stdout is getting the full log, with `-o -` or `-o /dev/stdout` options. It wasn't getting in the latter case.
=> FW/Logging: fix printing the "skip-reason" YAML field to stdout

bats/sanity-check/20-selftests.bats, framework/topology.cpp
Commit 5027ab76b4614e8d42a48487ae463c4935dfdeea (PR #327) made apply_cpuset_param() create a new array of `cpu_info`, but we didn't ensure it was sorted like it needed to be.
I could just call `reorder_cpus()` again, but everyone knows that `std::sort` is asymptotically O(n log n), while inserting while keeping the list sorted is O(log n) (though we're iterating over n elements, so the whole function is still O(n log n); oh well).
=> FW/Topology: fix the use of --cpuset out of order

framework/sandstone_context_dump.cpp
"0x%08u" was wrong. I was trying to figure out why the printed value made no sense:
```
mxcsr = 0x00008064 [ IM DM ZM OM UM PM RC=nearest ]
```
The raw value did not seem to match the flags it decoded.
Now it does:
```
mxcsr = 0x00001f80 [ IM DM ZM OM UM PM RC=nearest ]
```
=> FW/ContextDump: fix printing the raw value of the MXCSR

framework/topology.cpp
Since 9ed9a0c6c1c87304f80af746e2e996803f86304d (PR #321), the `cpu_info` array is sorted, so we know the highest numbered package is last. Additionally, because we sort in unsigned, we know that any unknown package IDs will be stored last too with an id of -1. That means we can resize the `packages` vector only once... though for most people once is all they were seeing anyway.
=> FW/Topology: Cleanup build_topology()

framework/sandstone.cpp, framework/sandstone.h, framework/topology.cpp, framework/topology.h
This simplifies the `Topology` class, from a vector of vector of vectors to a vector of vector of spans: we make the `Topology::Thread` type be exactly the same as the `struct cpu_info` that we'd had since version 1, when everything was still in C. 
The functions are simplified to reduce memory allocations on the child side, which is on the critical path of test running. Benchmarks don't show significant improvement, but it's still there.
=> FW/Topology: simplify the Topology class and functions

framework/sandstone.cpp
I hadn't tested the new flags because I was only using the global override option in the command-line with the unmodified set of tests. Problem arises of a conflict from the new flags added in PR #353 (commit 0f218f5b872a1b1062641ba19c8ebf1c47c92c44) with PR #248 (commit c0d75bffbef27873e7afb4a229ba97ad2faa3558).
Thanks to @dawid-sabat for noticing.
=> FW: fix launching threads for the new test schedule methods

framework/selftest.cpp
We can't #include <cpuid.h>, as that's an x86-64-specific header.
=> FW/child_debug: fix build outside of x86-64

framework/sandstone_context_dump.cpp
It was just garbage we were printing, because the `mask` variable had the original value of -1 that indicated what we'd like printed, not what we had available to print.
This has been there for a long time, but I think that it was only with commit fe984441511792bbd2e206f2e872f16d80e9dd1c (PR #357) that it got triggered. I began seeing this on our real SNB and HSW machines:
```
zmm0  = 0000000000000003:0000000000004e20 0acc9940a947333e:3a262354f539e18f
```
Obviously there's no ZMM register prior to SKX, so the situation above was impossible. Note also that, despite the name, it printed only 256 bits. I also couldn't reproduce on my HSW or SKL laptops, nor my CFL NUC, until I tried a release binary. Then I noticed that the buffer transferred from the XSAVE buffer was only 512 bytes (the …
=> FW/ContextDump: fix printing of XSAVE state when none was present

docs/writing_tests.md
Changes in example document for `meson` file are outdated.
Signed-off-by: Alex V Jaramillo <alex.v.jaramillo@intel.com>
=> docs: fix errors in writing_tests guide

framework/sandstone.cpp, framework/sysdeps/linux/cpu_affinity.cpp, framework/topology.cpp, framework/topology.h, framework/unit-tests/topology_tests.cpp
This allows us to go beyond the 1024 logical processor limit that the tool currently has. That number is very close to what an 8-socket Sapphire Rapids may have (896 for 56 cores per socket, 960 for 60 cores per socket) and is exceeded for servers with more than 8 sockets.
Plus, update the `ambient_logical_processor_set()` for Linux and FreeBSD not to use a variable sized to `CPU_SETSIZE` (1024), but instead also allocate dynamically (on the stack).
Last `MAX_THREADS` user bites the dust!
=> FW: make LogicalProcessorSet dynamically-sized

framework/cpuid_internal.h
We need to check if subleaf 0 told us that subleaf 1 is enabled, instead of relying on the registers being set to zero. Apparently, Sandy Bridge was buggy (see https://gcc.gnu.org/pipermail/gcc-patches/2023-August/626618.html and https://reviews.llvm.org/D156963).
Then enable extracting from register EDX there.
=> FW/cpuid: get the details from Leaf 7, subleaf 1, EDX register

framework/meson.build, framework/sandstone_ssl.cpp
OpenSSL 1.1 is about to EOL this September, so we are no longer supporting it.
Support for OpenSSL 3.0 remain unchanged.
=> FW/sandstone_ssl: Drop OpenSSL 1.1 support

bats/sanity-check/20-selftests.bats, bats/yamltest.py, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h
This adds the --max-cores-per-slice mode that limits the number of cores available in a given slice. This option can also be used to enable slicing even we heuristically wouldn't do it. It also un-deprecates the--np-slicing option to force the slicing feature to be disabled.
This PR also includes the ability to have multiple main threads (one per slice).
=> FW: add the --max-cores-per-slice and the beginnings of slicing

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp
This concludes the main development of the "socket separation" feature, by finally implementing parallel-slicing by default for all tests. There are still some clean-ups and minor tweaks that may go in.
For example, the formula as implemented in this commit probably deserves some attention. For a CPU like the 144-core Sierra Forest, the ideal plan would be 6 slices of 24 cores, but the formula calculates 5 slices (4x32 and one of 16).
The logging output may still change too.
=> FW: add proper test slice planning

framework/sysdeps/linux/msr.c
Commit 12cb9e6491ca61d4d4af08d26bb06c2ff3595013 ("don't keep trying to open the /dev/ MSR nodes if we get EACCES") added the early return, but forgot to set errno.
=> FW/MSR: set errno before the early return

framework/sandstone.cpp, framework/sandstone_p.h
Whenever the number of cores in the socket is a multiple of three fourths the target (24 instead of 32), we use this secondary division to avoid having an unbalanced last slice. This makes a 144-core socket like the announced Sierra Forest instead run 6 slices of 24 cores instead of 5 slices of 32 and one final of 16. I don't have any information whether this makes any difference to the performance of the system, but given that it will have one gross of sockets hints that the actual organisation of the cores on the die may have something to do with dozens.
The effect of having an extra child (6 instead of 5) should be negligible and could be compensated by the fact that each child only needs to start 24 threads -- the longest path for that system will be 6+24 = 30 clone() system calls, …
=> FW/Slicing: amend the test heuristic to add a secondary maximum

framework/sandstone.cpp, framework/sandstone_p.h
We were using for_each_main_thread() in the child process, which is wrong, because we run one child per slice, so there's only one main thread. This was causing some slices in the test-tests mode to conclude the test had failed, not because the test had, but because one of the other slices had marked the test's test as failed.
```yaml
threads:
- thread: main
messages:
- { level: info, text: 'I> Test memory use: (6076 - 2996) / 4 = 770 kB' }
- thread: main 1
messages:
- { level: info, text: 'I> Test memory use: (6068 - 2868) / 4 = 800 kB' }
- { level: error, text: 'E> Test ran shorter than expected: 24.472 ms (desired 1000.000 ms, min 750.000 ms)' }
- { level: info, text: 'I> Inner loop average duration: 5.038 ms' }
- thread: 4
id: { logical: 2, package: 0, core: 2, thread: 0, family: 6, …
```
=> FW/test-tests: fix race condition in checking the main thread(s)

framework/logging.cpp, framework/sandstone_p.h
This was mostly harmless and caused only a logging problem. It went unnoticed because if said slice had been run at least once (and hadn't failed the last time), nothing got printed.
We only initialise the `PerThreadData::Main` structure inside the child, so if there was no child, the block would have been left zeroed. And zero `fail_time` means "failed", causing the loggers to print the headers:
```yaml
- test: ifs
details: { quality: production, description: "Intel In-Field Scan (IFS) hardware selftest" }
state: { seed: 'LCG:788160728', iteration: 0, retry: false }
time-at-start: { elapsed:      0.000, now: !!timestamp '2023-08-17T23:05:19Z' }
result: skip
skip-category: ResourceIssueSkipCategory
skip-reason: 'could not open intel_ifs_0/run_test for writing (not running as root?): …
```
=> FW/Logging: Fix incorrect inspection of slices that didn't run

tests/mce_check/mce_check.cpp
We must update the variable after we've used it. Otherwise, we get:
```
Main thread:
- 'W> Platform issue: Thermal events detected (0 since start).'
```
Which is slightly less than fully useful.
=> mce_check: fix printing the count of thermal events

framework/sandstone.cpp
Truncated outputs of what the change does:
Before
`# SKIP (CpuNotSupportedSkipCategory : SKIP reason: test requires amx-bf16,amx-tile)`
After
`# SKIP (CpuNotSupportedSkipCategory : test requires amx-bf16,amx-tile)`
=> FW: Remove "SKIP reason:" message in log_skip as it is redundant

framework/sandstone.cpp
There's no (remaining) reason why that check should be way up, before the memory footprint check.
=> FW/test-test: move the test failure check closer to where it's used

framework/sandstone.cpp
See the comment for the description of the problem. Prior to the multi-children rewrite in commit 37cb3e5404eea2847c5da5fe576be0268282b8ee ("FW: rewrite wait_for_child() as wait_for_children()"), the effect of `poll(2)` always returning immediately was that we'd immediately go into `forkfd_wait()`:
```c++
EINTR_LOOP(ret, forkfd_wait(pfd[0].fd, &info, nullptr));
```
That means the child debugging wouldn't work, but the user would otherwise see no ill effects.
With the rewrite, I added a WNOHANG flag:
```c++
struct forkfd_info info;
EINTR_LOOP(ret, forkfd_wait4(pfd.fd, &info, WNOHANG, nullptr));
...
forkfd_close(pfd.fd);
pfd.fd = -1;
pfd.events = 0;
children.handles[i] = 0;
children.results[i] = test_result_from_exit_code(info);
```
This causes `waitid(2)` (inside `forkfd_wait4()`) to …
=> FW/forkfd: add a workaround against the Red Hat buggy 4.18 backport

tests/ifs/ifs.c
Because this test is sequential, its runtime is proportional to the number of cores being tested. The time for each Scan test is at most 200 ms (per Intel documentation). This will cause the test's target time to be set at a minimum to this value, which then will inform the test's timeout.
We're not bothering to try and find the exact number of cores that are going to be tested, so we may overestimate the minimum duration by half.
This will make a difference for a system with more than 225 logical processors because the formula in `test_timeout()` will go above the 5-minute default:
```c++
ShortDuration result = regular_duration * 5 + 30s;
if (result < 300s)
result = 300s;
```
=> ifs: add a preinit function to set the minimum duration

framework/sysdeps/generic/kvm.c, framework/sysdeps/linux/kvm.c
Changes that implement the new style of log_skip in kvm tests in opendcdiag
=> Implementation of log_skip on EXIT_SKIP for kvm.c tests

framework/sandstone_ssl_rand.cpp
Check OpenSSL is working before loading the random provider.
Fixes #400
=> FW/sandstone_rand_ssl: Fix crash when OpenSSL version not supported.

framework/sandstone.cpp, framework/sysdeps/unix/child_debug.cpp
Lost in commit 37cb3e5404eea2847c5da5fe576be0268282b8ee.
=> FW/child_debug: restore debug_hung_child() in case of hung children

framework/sandstone.cpp, framework/sandstone.h
This is useful API for the tests that manage the topology of their execution, i.e. group threads by CPU packages (sockets).
=> FW: add num_packages() API.

bats/sanity-check/20-selftests.bats
Commit 12f2f41b29f67527a0e5d3e4d1315d0efd12863b replaced grep with Python because FreeBSD doesn't have GNU grep, so it doesn't have --perl- regexp. However, I made two big blunders with the Python usage: first, the Python interpreter does not accept multiple `-c` arguments, and second I forgot to pass `"$value"` to it to match what we had extracted.
Effectively, this made all test_yaml_regexp pass, regardless of whether it matched anything or not.
=> CI/Bats: fix test_yaml_regexp

bats/sanity-check/20-selftests.bats
Commit 3ce88aad5f0adf0093a54c49f4926c6bf4c95132 (PR #404) fixed the regexp but I only tested debug builds, for which we were enforcing the topology to single-threaded. When run on real machines, sometimes it's the thread 1 that crashes first.
So we need to restrict to only threads 0 to get an "X".
=> CI/Bats: restrict non-fake topologies to threads 0

framework/sysdeps/unix/child_debug.cpp
Otherwise the second or further child that crashed could end up not being able to report it:
```
7543: 0.000043834 sendmsg(4,{...},MSG_NOSIGNAL) = 3032 (0xbd8)
37544: 0.000013963 sendmsg(4,{...},MSG_NOSIGNAL) ERR#55 'No buffer space available'
37540: 0.000017625 recvmsg(3,{...},0) = 3032 (0xbd8)
37540: 0.000008499 recvmsg(3,0x820cfb7b0,0)      ERR#35 'Resource temporarily unavailable'
```
=> FW/child_debug: multiply the buffer size by the number of slices

framework/sysdeps/unix/child_debug.cpp
This fixes a race condition, because the draining of the socket depended on the order in which we'd get the SIGCHLD / pidfd activation versus the socket. I hadn't observed this on Linux, but it can happen there two: if the parent process is woken up after two children have crashed, we'd only get the context of one.
If this race condition happened, we'd probably blame the next process as a crash too. While that doesn't detection worse (we've already had a crash), it could complicate debugging of the part.
=> FW/child_debug: ensure we drain the queue of crash information

bats/sanity-check/20-selftests.bats, framework/sysdeps/unix/child_debug.cpp
On FreeBSD, the SNDBUF is only 2kB by default while the RCVBUF is 16kB, so we need to increase it in order to pass the AVX512 state. We were getting EMSGSIZE when we tried:
```
13804: 0.000012265 sendmsg(4,{NULL,0,[{"\M-l5\0\0\0\0\0\0\0\M-N\M-F)\b\0"...,56},{"\0\0\0\0\0\0\0\0x\a\0\0\0\0\0\0@"...,800},{"\M^?\0\0\0\0\0\0\0\0\0\0\0\0\0\0"...,2176}],3,{},0,0},MSG_NOSIGNAL) ERR#40 'Message too long'
```
=> FW/child_debug: check SO_SNDBUF instead of SO_RCVBUF

bats/sanity-check/20-selftests.bats
They differ with different libcs.
Current glibc's SIGABRT is either "Aborted" or sometimes, weirdly, "IOT instruction" (because SIGIOT, an old PDP-11 name, is aliased to SIGABRT). On FreeBSD, it's "Abort trap".
=> CI/Bats: use Python to get the Unix signal descriptions

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/selftest.cpp
This was very useful for us in the past few days trying to figure out why tests were failing in the CI but only on certain machines. A crude version of this change revealed that all the tests were consuming less than 50% CPU and had a massive amount of kernel time and involuntary context-switches. That is, they were competing for CPU time with something else (a runaway buggy test on one machine, a runaway VSCode in another[1]).
Regular `timedpass_busywait` on a 4-core TGL:
```yaml
- test: selftest_timedpass_busywait
time-at-start: { elapsed:      0.000, now: !!timestamp '2023-08-31T20:23:30Z' }
result: pass
time-at-end:   { elapsed:    200.000, now: !!timestamp '2023-08-31T20:23:30Z' }
test-runtime: 200.433
threads:
- thread: main
runtime: 200.421
resource-usage: { utime: 1560.711, stime: …
```
=> FW/Logging: log the per-slice resource-consumption information

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/selftest.cpp
This is where it used to be, in the earliest versions of the framework. I moved it to the child on d0edbae7ad0dde41a3a1b2a41ebfc957f16b409f (2021-03-19) in the old repository:
```
FW: move the per-test check on CPU features and timing into the child
This means we'll launch a child for tests that will be skipped, thus
adding a bit of overhead. But it simplifies logging (especially for
Windows support).
```
Before this, we were getting away with the `FILE *` logging across parent and child on Linux, but that was a ticking time bomb. Therefore, I simplified by moving all the per-thread logging into the child.
Commit 040bc365e8eeddf27b4a4a892dfb2a7a2a5cb912 (#286) removed the `FILE*` -based logging and moreover 8294f1ae3a1cf3503333bace9954af2e6c4b836f (#324) kept the file descriptors open, so …
=> FW: move up the CPUID detection to the parent process

framework/sandstone.cpp
We weren't closing / replacing the handle, so after the first child exited, `WaitForMultipleObjects()` would keep signalling the same child every time. As a consequence, we'd never get the results of the other children, but we'd keep counting children_left down.
`WaitForMultipleObjects` fails with `ERROR_INVALID_HANDLE` if one of the handles is `INVALID_HANDLE_VALUE` (duh!) so we can't use that. We can't repeat the same handle either. The expected solution is to rearrange the array, but instead of that we replace with a dummy, non-signalled handle that will be closed by `~ChildrenList`.
Now this reports properly:
```yaml
- thread: main
runtime: 18.816
messages:
- thread: main 1
runtime: 1013.116
messages:
- { level: error, text: 'E> Child 384 did not exit, using TerminateProcess()' }
```
=> FW/Win32: fix waiting_for_children() when waiting for multiple children

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/selftest.cpp, framework/sysdeps/windows/cpu_affinity.cpp
Instead of statefully depending on the previous count of members in each group, just store them in the bits of the `LogicalProcessor` variable. This turns the operations that used to be O(n) to O(1).
More importantly, this means we don't depend on stateful data that needed to be initialised. It was only initialised by `ambient_logical_processor_set()`, which the child process stopped calling (probably in commit bbf1ad64067897803fdd612e992aa7c827bf1baa). That was an intentional change, because the child should never need to know the full system's ambient processor set, only what the parent process tells it to care about.
As a side-effect of that, the child process wouldn't have the state initialised, so `processor_group_for()` would always return zero and `processor_in_group()` would …
=> FW/Win32: statelessly map LogicalProcessor to PROCESSOR_NUMBER

framework/sandstone.cpp, framework/sandstone_p.h, framework/selftest.cpp
We've had a customer asking to be able to say --retest-on-failure=99 so they can get proper 1% granularity.
=> FW: increase the --retest-on-failure maximum to 128

framework/topology.cpp
`strtok()` by necessity must modify the input by adding NULs, and this causes the logging to improperly print parameters with commas.
Previously:
```
$ ./opendcdiag --quick -o - --cpuset c0,c2
command-line: 'opendcdiag --quick -o - --cpuset c0'
```
Now:
```
$ ./opendcdiag --quick -o - --cpuset c0,c2
command-line: 'opendcdiag --quick -o - --cpuset c0,c2'
```
=> FW/Topology: make a copy of the argv contents in apply_cpuset_param()

framework/sandstone.cpp
Before:
```yaml
time-at-start: { elapsed:      0.000, now: !!timestamp '2023-09-06T21:09:16Z' }
result: skip
skip-category: UnknownSkipCategory
skip-reason: Unknown, check main thread message for details or use -vv option for more info
time-at-end:   { elapsed:      0.000, now: !!timestamp '2023-09-06T21:09:16Z' }
```
After:
```yaml
time-at-start: { elapsed:      0.000, now: !!timestamp '2023-09-06T21:26:25Z' }
result: skip
skip-category: RuntimeSkipCategory
skip-reason: 'Unexpected OS error: Permission denied'
time-at-end:   { elapsed:      0.000, now: !!timestamp '2023-09-06T21:26:25Z' }
```
=> FW: re-add a log_skip if a test init() returns a negative errno

framework/logging.cpp
I've found myself wondering about this in some customer logs. Usually they send failures, which will include the version in the failure header, but it's easier if it is near the top.
=> FW/Logging: include the tool's version in the TAP header too

framework/sandstone.cpp, framework/sysdeps/windows/cpu_affinity.cpp, framework/sysdeps/windows/meson.build, framework/sysdeps/windows/win32_perror.c, framework/sysdeps/windows/win32_stdlib.h
We're expecting that the child processes are restricted to a single Windows Processor Group, in which case we can ask the OS to set the affinity to that group. This will affect the child process' main thread only, so it's not a big deal if we don't do anything. It's actually more important that we be quick.
Also print the error message from `pin_to_logical_processor()` if there's a failure.
=> FW/Win32: implement pin_to_logical_processors()

framework/logging.cpp
This is only useful in the case the logging framework crashes when attempting to read the messages of the threads and format them, but in the 4 years since I've been maintaining this, that has never happened. So save some system calls.
=> FW/Logging: remove logging_flush() from the middle of the test results

framework/logging.cpp
This is right after we print the test that is about to start, so is a logical place to flush the log to filesystem.
I noticed this on a defective machine that rebooted because of a test, that the actual log file said a test had finished and passed:
```yaml
time-at-start: { elapsed: 13592188.000, now: !!timestamp '2023-10-25T02:06:39Z' }
result: pass
time-at-end:   { elapsed: 13592280.000, now: !!timestamp '2023-10-25T02:06:39Z' }
test-runtime: 92.027
```
But the terminal from which I launched the tool (tmux rules!) logged the next test starting:
```yaml
- test: xxxxx
time-at-start: { elapsed: 13592280.000, now: !!timestamp '2023-10-25T02:06:39Z' }
```
=> FW/Logging: add logging_flush() to logging_init()

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp
The rewrite in commit 37cb3e5404eea2847c5da5fe576be0268282b8ee for wait_for_children() accidentally broke the handling of interruptions by signals on Unix systems, which exists to ensure all the processes get interrupted if the parent process is.
Handling of SIGHUP and SIGTERM was easy, since single_wait() was already returning the correct signal number, but wait_for_all_children() wasn't acting on it. Handling of SIGINT required remembering we had been interrupted once.
Fixes #429.
=> FW/Unix: fix handling of signals in wait_for_children()

framework/topology.cpp
Because otherwise the warning output on mismatch says "package -1".
```
WARNING: Inconsistent CPU information detected. Reference socket 0 is family 0x06, model 0x8f, stepping 0x06
WARNING: CPU 56 on socket -1 differs from socket 0: family 0x06 model 0x8f, stepping 0x08.
```
=> FW/Topology: fill in the topology before family/model/stepping

framework/meson.build
Meson has this interesting .partial_dependency() trick that does exactly what we want.
https://mesonbuild.com/Reference-manual_returned_dep.html#deppartial_dependency
=> FW/Meson: ensure we don't accidentally link to OpenSSL if dlopen()ing it

framework/logging.cpp, framework/sandstone.h, framework/selftest.cpp
The following 3 skip categories are added
TestResourceIssueSkipCategory
CpuTopologyIssueSkipCategory
OSResourceIssueSkipCategory
Removed Category: ThreadIssueSkipCategory
**Please do not merge yet**
=> FW: Add new skip categories

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/sandstone_p.h, framework/sysdeps/windows/fnmatch.c, framework/sysdeps/windows/fnmatch.h, framework/sysdeps/windows/meson.build, framework/test_selectors/SelectorFactory.cpp, framework/test_selectors/SelectorFactory.h, framework/test_selectors/TestrunSelectorBase.h, meson.build
Centralises the handling from test files and command-line, and fixes the missing preinit and group initialisation from test files.
[ChangeLog][Framework] Added the --ignore-unknown-tests option, to ignore unknown tests in the --enable and --disable options.
=> FW: add --ignore-unknown-tests option

framework/sysdeps/linux/interrupt_monitor.cpp
When some CPUs are offlined by the system adminstrator via `/sys/devices/system/cpu/cpuN/online`, the column numbers and CPU numbers in `/proc/interrupts` will no longer match.
For example, if I turn off CPUs 10 to 19 on a 14-core system, the header will be:
```
CPU0       CPU1       CPU2       CPU3       CPU4       CPU5       CPU6       CPU7       CPU8       CPU9       CPU20      CPU21      CPU22      CPU23      CPU24      CPU25      CPU26      CPU27
```
So we must parse the first line to create tha mapping and we must do so every time we read this file, in case it changed. If it did, the mce_check will likely report an error.
=> FW/InterruptMonitor: fix parsing /proc/interrupts with offlined CPUs

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/selftest.cpp
Some tests (e.g. with locks) requires post-run checkin, if anything is inconsistent, test is expected to fail.
Both patterns (logging error(s) and returning non-SUCCESS value) from test_cleanup function are handled properly and report appropriate state in the log. Potential group SKIPs are handled in limited scope.
=> Option to fail a test in cleanup.

framework/sandstone.cpp
If the application is "in between" test execution mode (waits for credits to execute tests), non-fatal signals are handled with usleep() and forces application loop to stop.
Appropriate log is added, the application returns current test execution status (not 'interrupted').
=> Handling signals between tests

bats/sanity-check/20-selftests.bats, framework/selftest.cpp
Some "false" conflicting names (logskip) of selftests replaced with the ones which not fall into "selftest_logs*" mask.
This is intended to fix integration builds (selftest phase).
=> Selftests names fixed to fix CI issues.

bats/sanity-check/20-selftests.bats, bats/testenv.bash
That function enforces creating the file in a temporary dir, unlike mktemp command.
=> CI/Bats: use mktempfile in testenv.bash

framework/topology.cpp
GitHub's updated CI added AMD CPUs, which don't appear to support getting the topology information using CPUID 0xb (x2API) - https://wiki.osdev.org/Detecting_CPU_Topology_(80x86) confirms:
>  *INTEL: CPUID eax=0x0000000B*
> For Intel CPUs (and not AMD), this CPUID function tells you [...]
So this implements a software fallback for both Linux and Windows. The Linux fallback already existed, but wasn't getting triggered because we assumed `fill_topo_cpuid()` would always succeed.
There's now a new Windows implementation using [`GetLogicalProcessorInformationEx`](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlogicalprocessorinformationex). We won't get the correct core numbers on Intel CPUs using this, but it's better than nothing.
On my Alder Lake …
=> FW/Topology: fix running in GitHub's updated CI

bats/sanity-check/20-selftests.bats, framework/logging.cpp
This will remove redundant suffix "SkipCategory" attached to skip-category message in the log.
Before the change:
```
result: skip
skip-category: CpuNotSupportedSkipCategory
skip-reason: 'test requires amx-tile'
```
After the change:
```
result: skip
skip-category: CpuNotSupported
skip-reason: 'test requires amx-tile'
```
=> FW/Logging: Remove redundant "SkipCategory"

framework/logging.cpp
We were "abusing" the value of -1, so stop doing that. The TAP and key-value logging formats didn't need the message severity at all, so split off their implementation from the YAML one, which does, except when the message was a skip.
=> FW/Logging: Refactor format_and_print_message()

framework/frequency_manager.hpp, framework/sandstone.cpp, framework/sandstone_p.h
This is part of the frequency manager support to opendcdiag. If this option is used, every test will run at precalculated different frequencies per fracture of the test within it's allocated time to run.
This option only works when opendcdiag's user is root.
Usage example: ./opendcdiag -vv -e eigen_gemm_double14 --vary-frequency
Frequency change heursitics: 
Pre-calculated different frequency levels varying from mininum supported frequency to maximum supported frequency.
E.g., min_freq = 1.2Ghz, max_freq = 3.6Ghz, different frequency levels calculated in the below order
3.6, 1.2, 2.4, 3.0, 1.8, 3.3, 2.7, 1.5.
Every fracture selects the above frequency for all cpus and sets it. 
At the end when sandstone exits, it restores the system to it's initial state.
**Validation**:
validated this on …
=> FW: Add --vary-frequency option

framework/logging.cpp, framework/sandstone.h, framework/selftest.cpp, framework/sysdeps/linux/kvm.c, tests/eigen_sparse/eigen_sparse.cpp, tests/ifs/ifs.c, tests/openssl/openssl_sha.cpp
We have decided to split ResourceIssueSkipCategory into, roughly, two: TestResourceIssueSkipCategory and OSResourceIssueSkipCategory. This foments  correct usages of the categories by the test writers as well as helps analyzing the logs. The usages of ResourceIssueSkipCategory were removed as well as the category itself. Since it existed ever so briefly, there's no need to make it a non-breaking change.
=> Remove ResourceIssueSkipCategory and replace its usages.

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp
Do not run triage by default. Add an option `--triage` to force the previous behavior.
[ChangeLog][Framework] Change the default behavior to not run triage. Add --triage option to force the previous behavior.
=> Change triage default behavior

framework/sandstone.cpp, framework/scripts/x86simd_generate.pl
This reverts commit 71643880fb56af4f6e8216ac8a25c1caa8c5690c. We don't want natural sorting of the array, we want reverse natural sorting.
The loop in `dump_cpu_info()` depends on the list being sorted from most featureful to least. We could reverse the iteration there but it's easier this way.
Before:
```
$ $objdir/opendcdiag --dump-cpu-info
Detected CPU: Core2; family-model-stepping (hex): 06-8c-01; CPU features: clflush,sse2,pclmul,fma,sse4.2,movbe,popcnt,aes,avx,f16c,rdrnd,fsgsbase,bmi,avx2,bmi2,avx512f,avx512dq,rdseed,adx,avx512ifma,clflushopt,clwb,avx512cd,sha,avx512bw,avx512vl,avx512vbmi,ospke,avx512vbmi2,shstk,gfni,vaes,vpclmulqdq,avx512vnni,avx512bitalg,avx512vpopcntdq,movdiri,movdir64b,ibt,lzcnt
```
Now:
```
$ $objdir/opendcdiag --dump-cpu-info
Detected CPU: Tiger Lake; …
```
=> Fix --dump-cpu-info detection

framework/logging.cpp
Fixes #452. Now:
```
$ $objdir/opendcdiag --output-format=tap --selftests -e selftest_timedpass_busywait --quick
THIS IS AN UNOPTIMIZED BUILD: DON'T TRUST TEST TIMING!
ok   1 selftest_timedpass_busywait # (beta test) 
ok   2 mce_check
exit: pass
```
=> FW/Logging/TAP: ensure there's a space before #

framework/sandstone_p.h
For `AutoClosingFile` and `Pipe`, add the missing copy & move constructor and assignment operators. Nowhere in our code were they used incorrectly, but this helps ensure they never do.
For `scopeExit()::Scope`, just delete them all.
=> FW: Fix rule-of-five violations

framework/logging.cpp
The `add_value` lambda was receiving a `std::string` by value, which was inefficient because it copied the string.
=> FW/Logging: performance improvement: don't copy strings

framework/logging.cpp
It used to be a small type (only 8 bytes) before commit b55f5648bcfbc1f1c18e87576a0e039f803831fe. It's still trivial so the compiler is likely to understand no copying is required, but let's help it along.
=> FW/Logging: pass ChildExitStatus by const-reference

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_child_debug_common.h, framework/sandstone_context_dump.cpp, framework/sandstone_context_dump.h, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/windows/child_debug.cpp, framework/sysdeps/windows/tmpfile.c, framework/sysdeps/windows/win32_errorstrings.h
Fixes #314.
Now we're getting:
```yaml
- level: info
text: |1
Registers:
rax   = 0x000000000000002a (42)
rbx   = 0x0000000000000000 (0)
rcx   = 0x000000000000feed
rdx   = 0x0000000000c0ffee
rsi   = 0x000002a23c9873e0
rdi   = 0x00000000dfef324d
rbp   = 0x000000e6ed5ffc10
rsp   = 0x000000e6ed5ffb90
r8    = 0x00000000dfef324d
r9    = 0x000002a23c9873e0
r10   = 0x0000000000000011 (17)
r11   = 0x000000e6ed5ffcc0
r12   = 0x0000000000000000 (0)
r13   = 0x0000000000000000 (0)
r14   = 0x0000000000000000 (0)
r15   = 0x0000000000000000 (0)
rip   = 0x00007ff6043e9896
flags = 0x00010246 [ PF ZF IF RF ]
fs    = 0x53
gs    = 0x2b
fcw   = 0x37f
fsw   = 0x3000 [ top=6 ]
ftw   = 0xc0
st(0) = 4000c90fdaa22168c235 (0xc.90fdaa22168c235p-2)
st(1) = 3fff8000000000000000 (0x8p-3)
st(2) = 00000000000000000000 …
```
=> FW/Win32: add a crash context dumper for Windows

framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/sandstone_utils.h
We exited in three different places but only one duplicated the call to `logging_close_global()`. Only the main exit remembered to call `print_application_footer()` and restore any system state we modified (in the current version, the `--vary-frequency` state).
This centralizes everything in a function that Does The Right Thing™, plus removes a magic constant in the code.
Our exit codes are:
* EXIT_SUCCESS (0) - all tests passed (or skipped)
* EXIT_FAILURE (1) - at least one test failed
* EXIT_INVALID (2) - inconclusive result
* EXIT_ABORTED (3) - (documentation only) used by abort() on Windows
* other values (64-78, >=200) - unable to start, logging hasn't started
The shell will report crash (signal) exits by OR'ing the signal number with 128.
=> FW: add cleanup_global() to centralize application exiting

framework/sysdeps/linux/kvm.c
The fail_entry pointer initialised at the top of the function was bogus because ctx->runs was still NULL. We need those pointers only after ctx->runs is allocated by `kvm_generic_add_vcpu()`.
Doing the casting just before the switch should help the compiler in realising they don't need to be saved anywhere.
=> FW/kvm: fix crash when we get a KVM_EXIT_ENTRY_FAIL condition

framework/sandstone.cpp
We printed "--max-log-data" (with an extra dash) when its argument failed to properly parse as a number.
=> FW: fix spelling of the "--max-logdata" option name

bats/sanity-check/20-selftests.bats, framework/selftest.cpp, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/windows/child_debug.cpp
This can happen when exceptions are thrown for other reasons, in particular that of C++ exceptions. Both GCC and MSVC use the SEH mechanism to handle their exceptions. We didn't catch this before because the most self-tests are run with --on-crash=core, so the vectored exception handler wasn't installed.
Before:
```yaml
- test: selftest_cxxthrowcatch
result: crash
result-details: { crashed: true, core-dump: false, code: 0x20474343, reason: '???' }
fail: { cpu-mask: 'X', time-to-fail: null, seed: 'AES:1d1726ac3d4d55dd78077b0a6de46d10e2e8d953c2b2aa2287f884f5921b92ef'}
time-at-end:   { elapsed:     21.343, now: !!timestamp '2023-11-23T23:55:02Z' }
test-runtime: 19.280
threads:
- thread: 0
id: { logical-group:  0, logical:  0, package: 0, core: 0, thread: 0 }
messages:
- { level: error, text: …
```
=> FW/Win32/child_debug: don't stop execution on non-system exceptions

framework/sandstone.cpp
We were calling `wait_for_children()` even with `-fno`, so it reset the `children.results` vector back to empty.
=> FW: fix getting messages from the main thread under -fno

framework/sandstone.cpp, framework/sandstone_thread.cpp
Either we can actually ignore because they don't make a difference or there's no recourse in case it fails, so we may as well let the started threads crash.
=> FW: add IGNORE_RETVAL() for mprotect()

framework/sysdeps/linux/kvm.c
This is to help debugging why the test failed, most often when writing new tests and trying to figure out why they're not behaving as expected. That includes `KVM_EXIT_FAIL_ENTRY` cases when we set up the state incorrectly.
Now, for every failure, we'll get something like:
```yaml
- level: info
text: |1
I> Register dump:
rax = 0x0000000000000001 rbx = 0x0000000000000000 rcx = 0x0000000000000000 rdx = 0x0000000000000600
rsi = 0x0000000000000000 rdi = 0x0000000000000000 rsp = 0x00000000005ff000 rbp = 0x00000000005ff000
r8  = 0x0000000000000000 r9  = 0x0000000000000000 rcx = 0x0000000000000000 r11 = 0x0000000000000000
r12 = 0x0000000000000000 r13 = 0x0000000000000000 r14 = 0x0000000000000000 r15 = 0x0000000000000000
rip = 0x0000000000300006 rflags = 0x0000000000000002 []
cs  = 0x0008 base = …
```
=> FW/kvm: always print the vCPU register state on failure

framework/sandstone_test_utils.h
Added a constructor, copy constructor and copy assignment operator to ManagedCodeBuffer to adhere to the Rule of Three. This ensures proper copying and management of dynamic memory in the class.
=> Implement Rule of Three in ManagedCodeBuffer

framework/sandstone_ssl.h
- Adding d2i to decode private/public key from a bio.
Signed-off-by: Alex V Jaramillo <alex.v.jaramillo@intel.com>
=> Enabling d2i key APIs

framework/sandstone_context_dump.cpp, framework/sandstone_context_dump.h
I had used `FILE *` originally so this code could be useful in C applications too (that's why it didn't use any of our own utilities either). But let's use std::string instead because that will allow me to get rid of `open_memstream()` and temporary files in the caller code.
Also, declare a `SandstoneMachineContext` type instead of doing #if on the declaration itself. This makes the declaration simpler.
=> FW/ContextDump: refactor to internally use std::string

framework/sysdeps/windows/futex.h
=> FW/Win32: fix compilation: it's WakeByAddressSingle

framework/scripts/generate_test_list.py
The generator updated according the discussion from PR #454. The commit includes two behavioural changes:
- default list is always "at the end" (when there's no matching list, either by name or features), location of this entry in the list is not important
- it is not required to name 'default' list (only a filename might be put into the option, without 'default' prefix)
- internal data model slightly changed: each file (by name) is parsed once, might be shared between lists for multiple generations.
If no matching list is defined during compilation (and selected with --use-builtin-test-list), appropriate warning is emitted in runtime.
Signed-off-by: Jarek Poswiata <jaroslaw.poswiata@intel.com>
[ChangeLog] Default list must be explicitly defined in the option. If no matching list is found …
=> FW: condition builtin testlist on CPU arch

framework/sandstone.cpp
The help information can get quite lengthy and does cause the actual error message to scroll up. Instead print short suggestion to use '--help' option when there's an error processing.
(Finding random stuff in my branches that is useful.)
=> Do not print help by default, instead suggest to use it.

framework/frequency_manager.hpp, framework/sandstone.cpp, framework/sandstone_p.h
This PR consists of 2 commits. 
First commit will re-factor already existing core frequency manager support so that it makes easier addition of uncore frequency manager support. This does not change any functionality of core frequency manager.
Second commit will add the actual uncore frequency manager support. This commit will add `--vary-uncore-frequency` option to opendcdiag. If this option is used, every test will run at pre-calculated different uncore frequency per fracture of the test within it's allocated time to run. Like core frequency manager, this option works only on linux and the user should be root.
Testing:
All tests are conducted on 2 socket BDX platform(18 core/socket). opendcdiag option used to measure uncore frequency
`opendcdiag -vv -e eigen_gemm_double14 -e zlib -t30s` …
=> Add Uncore frequency manager support.

framework/sysdeps/windows/aligned_alloc.cpp
This is an interesting function that allows us to avoid having to `memset()` ourselves (presumably, if the CRT knows it's zeroed, it wouldn't need to do it again). But WINE hasn't implemented it, so let's not rely on it.
=> FW/Win32: stop using _aligned_recalloc with UCRT

framework/frequency_manager.hpp
Return value of fscanf should be checked for EOF instead of relying on boolean logical operator.
Should be working fine:
```
./opendcdiag -vv -e eigen_gemm_double14 -e zlib -t30s --vary-frequency
./opendcdiag: Cannot find "userspace" scaling governor from the file: /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
```
=> FW: Fix bug in frequency manager

framework/sandstone.cpp
=> FW/Tests: enable list autodetection with --use-builtin-test-list

framework/logging.cpp
This is to enable debugging of third-party libraries that do have stdout-based debug logging enabled.
=> printf() logs messages on the console in debug builds

bats/sanity-check/20-selftests.bats, framework/topology.cpp
This is useful when you want to run on all logical processors except a few, and listing all 896 entries but those would be very tiring.
For example, for `--cpuset='!0,3'` on a 4-core system:
```yaml
cpu-info:
0: { logical: 4, package: 0, core: 0, thread: 1, family: 6, model: 0x8c, stepping: 1, microcode: 0xb6, ppin: null }
1: { logical: 1, package: 0, core: 1, thread: 0, family: 6, model: 0x8c, stepping: 1, microcode: 0xb6, ppin: null }
2: { logical: 5, package: 0, core: 1, thread: 1, family: 6, model: 0x8c, stepping: 1, microcode: 0xb6, ppin: null }
3: { logical: 2, package: 0, core: 2, thread: 0, family: 6, model: 0x8c, stepping: 1, microcode: 0xb6, ppin: null }
4: { logical: 6, package: 0, core: 2, thread: 1, family: 6, model: 0x8c, stepping: 1, microcode: 0xb6, ppin: null }
5: { …
```
=> FW: implement negated --cpuset option

framework/sandstone.cpp
optind points to the next option to be processed, so pass the argument to getopt to get the current index.
Before:
```
./opendcdiag: option '(null)' is ignored and will be removed in a future version.
```
After:
```
./opendcdiag: option 'schedule-by' is ignored and will be removed in a future version.
```
=> FW: Fix deprecation warning.

bats/sanity-check/20-selftests.bats, framework/selftest.cpp, framework/topology.cpp
We weren't rebuilding the cached topology if the resulting set was the same as the original. In general, that's a good thing, except when there was no cached topology in the first place...
=> FW/Topology: fix num_packages() in -f exec mode (i.e. Windows)

framework/amx_common.h
For GCC >= 12 and for Clang, we rely in it providing the intrinsics.
=> FW: do #include <immintrin.h> in amx_common.h

framework/sysdeps/generic/kvm.c
Current generic functions used in kvm are available only in linux, this change provides the same functions declaration for windows builds so a skip message can be printed.
Signed-off-by: Alex V Jaramillo <alex.v.jaramillo@intel.com>
=> kvm: windows skip generic functions

tests/meson.build, tests/openssl/openssl_sha.cpp
Before the change this test will not be build in windows. This change makes possible for the test to skip when executing in windows OS and prints a not supported in OS skip message.
=> openssl_sha: Print skip in windows

framework/sandstone.cpp
The HANDLEs are local to the current process. The PID can be used elsewhere, like Task Manager.
=> FW/Win32: print PIDs not HANDLEs when blaming frozen children

framework/sandstone_tests.cpp
Found in one of our internal builds:
```
../opendcdiag/framework/sandstone_tests.cpp: In function 'std::vector<test_cfg_info> load_test_list(std::ifstream&, SandstoneTestSet*, bool, std::vector<std::__cxx11::basic_string<char> >&)':
../opendcdiag/framework/sandstone_tests.cpp:197:35: error: aggregate 'std::stringstream msg_strm' has incomplete type and cannot be defined
```
=> FW: add missing #include for std::stringstream

bats/testenv.bash
Take into account the variable that might have been set before the run.
=> BATS: allow adding ASAN_OPTIONS externally.

.editorconfig
Adapt formatting rules for meson files.
* See: b4f390828337 ("Meson: Replace tabs with 4 spaces.")
Also, fix existing formatting rules-- there were some subtleties around `indent_size` and `tab_width` that were not grokked before, see commits for details.
=> editorconfig: meson.build formatting changes

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/sandstone_tests.h
Fixed #523
Looks like an off-by-one error where we skipped the last or first entry... resulting in reading one-past-the-end and a crash. Plus there was some dangling pointer dereferences I didn't investigate.
Instead, I removed the special Iterator class added by commit @e89cd594fcda062209c3fccf7fa7a34bbe62b58f (at my urging in the PR review), but it turns out to have been more complex than necessary and more harm than good. So this just cleans up by removing that iterator class completely and relying on `get_next_test()` function to do the looping.
=> FW: simplify the test iteration code to fix looping (-T)

bats/sanity-check/20-selftests.bats
This was added by commit 9601936870325fe2d857973bfd3f750135db0af0 and passed on my machine and in the CI, but I don't know how because it doesn't now. Maybe f60599d3b77d79dfd08a13b11c839b2dee98f352 has an effect.
In any case, we can't tell much about the time-at-end: `should_start_next_iteration()` only starts the next iteration if the remaining time until the deadline is more than the average iteration time. In CIs, we can't tell much about the average time and the deviation from the average for this next iteration can be huge.
=> CI: update the -T test

bats/sanity-check/20-selftests.bats
This test was added by commit 8c1466a1abea002f6eac023a390d546021a3d306 and is part of the standard `@positive` group of selftests. It appears to pass just fine under normal circumstances, but we have observed it to fail in:
- ASAN builds
- More than 10 threads
This appears to trigger some race condition inside libasan that causes the child processes to remain behind. When that happens, Bats hangs.
This problem does not affect the "selftest_freeze_fork" bats test because it runs with -n4 or fewer CPUs. Plus, in the freezing case, the framework will kill those child processes, so Bats won't hang.
=> CI/Bats: disable the selftest_timedpass_fork test for the silent run

bats/sanity-check/10-yaml-validate.bats, bats/sanity-check/20-selftests.bats, framework/sandstone.cpp
Remove the triage implementation. Deprecate `--triage` and `--no-triage` options. Clean up tests.
I think at this point it might be safe to do so.
=> FW: Remove triage implementation

framework/unit-tests/sandstone_data_tests.cpp
I don't know why it's suddenly started failing in the GitHub CI:
```
../framework/unit-tests/sandstone_data_tests.cpp:71:27: error: no member named 'setfill' in namespace 'std'
s << std::hex << std::setfill('0') << std::setw(8) << u;
~~~~~^
../framework/unit-tests/sandstone_data_tests.cpp:71:48: error: no member named 'setw' in namespace 'std'
s << std::hex << std::setfill('0') << std::setw(8) << u;
~~~~~^
```
=> Unit Tests: fix build - missing #include

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/sandstone_tests.cpp, framework/sandstone_tests.h
This refactors `SandstoneTestSet` to keep extra options in each test that is added to the roster. The only one for the moment is the requested duration, but this allows expanding later as needed. This restores the behaviour prior to e89cd594fcda062209c3fccf7fa7a34bbe62b58f.
Fixes #533.
=> FW/Tests: Allow test lists to specify different times for each test

framework/sandstone.cpp, framework/sandstone_tests.cpp, framework/sandstone_tests.h
Even though they apply to the command-line options --enable and --disable, this now matches better what the internal behaviour is.
=> FW/Tests: rename {enable,disable} to {add,remove}

framework/sysdeps/linux/kvm.c
Sometimes it is invalid right after creation.
=> FW/KVM: reset the SS descriptor before KVM entry

.github/workflows/pr.yaml
Repeat of #518 but for the other workload.
=> CI: Harden GitHub workflow permissions for pr.yaml

framework/sysdeps/linux/kvm.c
We previously tried to simply ensure that sregs.ss was set and not passed through from whatever the kernel gave us upon KVM_CREATE_VCPU. That has not sufficed: we are still getting KVM_EXIT_ENTRY_FAILs with an invalid SS descriptor state. So instead of attempting to work around the cache before KVM_RUN, let's just detect the symptom and force the vCPU to be recreated.
See https://lore.kernel.org/kvm/20240725175232.337266-1-mlevitsk@redhat.com/
=> FW/KVM: Work around the KVM/VMX cache bug (attempt #2)

framework/sandstone.cpp
Whenever we need to start an iteration, use proper entry point which does not skip quality checks and everything else that may need to be done.
If test 'mytest' was of beta quality. Before:
```
$ ./opendcdiag -e mytest --output-format tap -Tforever # force multiple iterations
ok 1 mce_check
ok 2 mytest
ok 3 mce_check
ok 4 mytest
ok 5 mce_check
<...>
```
After:
```
$ ./opendcdiag -e mytest --output-format tap -Tforever # force multiple iterations ok 1 mce_check
ok 2 mce_check
ok 3 mce_check
<... mytest is never ran, as it should be ..>
```
=> FW: Restart the test iteration properly.

framework/topology.cpp
This is not configurable but at least allows any tests that attempts to read the cache sizes to still run.
=> FW/Topology: allow mocking the CPU cache too

framework/sandstone.cpp, framework/sandstone.h, framework/sandstone_unittests_utils.cpp, framework/sandstone_unittests_utils.h, tests/ifs/ifs.c
Because if we load the next image, then we aren't retesting the same thing. We'd be testing the next image.
Logging with only `log_debug` to avoid creating unnecessary noise in the log output. We already know it's a retest.
=> IFS: don't load the next image if we are retesting a failure

.github/workflows/build.yaml
Especially when we advise to do so in README
libboost-dev contains only headers, non-header-only packages are in libboost-all-dev
=> CI: Install full boost package

.github/workflows/build.yaml
Reverting PR #555 which modified dependency on Boost from`libboost-dev` to `libboost-all-dev`, which was needed for command line parser refactoring. Initial round of review concluded that we'd like to keep a header-only dependency on Boost.
Also, `libboost-all-dev` introduces a large number of additional packages which cause a bit of problems in CI due to broken dependency chains in Debian Sid.
=> Reverting dependency on libboost-all-dev in CI

framework/sysdeps/unix/child_debug.cpp
The YAMA LSM[1] defaults[2] to denying a ptrace() to a process that isn't a child. That is the regular debugging behaviour: gdb launches the child, so it is allowed to trace its own children.
In OpenDCDiag's case, the parent process launches the debugger, so the debugger is a sibling, not a parent. That results in gdb getting an EPERM when we attempt to launch it for `--on-crash=backtrace` or `--on-hang=backtrace`. The child must grant explicit permission instead to allow a sibling debugger process to trace it.
[1] https://www.kernel.org/doc/Documentation/security/Yama.txt
[2] https://codebrowser.dev/linux/linux/security/yama/yama_lsm.c.html#ptrace_scope
=> FW/child_debug: allow debugging when a kernel LSM may be active

framework/sandstone.cpp
We want to give `.fracture_loop_count` value  priority over cmdline,
so that it won't execute more loops than that.
=> FW: reorganize current_max_loop_count assignment

framework/sandstone.cpp
This change removes the iteration condition for tests with quality lower that requested and add it before calling `run_one_test`. Also, a warning is logged for BETA tests.
Example:
For a test with `TEST_QUALITY_PROD`
```
$ ./builddir/opendcdiag -e smi_count
command-line: 'opendcdiag -e smi_count'
version: opendcdiag-7df166cfa4e4-dirty
exit: pass
```
For a test with `TEST_QUALITY_BETA`
```
$ ./builddir/opendcdiag -e simple_add
command-line: 'opendcdiag -e simple_add'
version: opendcdiag-7df166cfa4e4-dirty
Test simple_add is in BETA quality. Try again with --beta option.
exit: pass
```
=> Add message when running beta tests without `--beta` option

framework/logging.cpp
When the user does not provide us with a name for the log file, we generate one based on the current univesal time. This change makes OpenDCDiag refuse to overwrite such an existing file.
The file name contains the current timestamp down to microseconds, so it's extremely unlikely one *can* match an existing file anyway.
=> FW/Logging: refuse to overwrite time-based log files

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp, framework/sysdeps/windows/child_debug.cpp
Amends commit bdc345642e79555cfbfc62a34028d75ddf4b6ad8 ("FW/child_debug: use futexes to make the child wait for gdb") and more importantly commit b92a2efd7eab9cbb9ad4d1a4289304ec26be1b31 ("FW/SharedMemory: add support for multiple main threads").
This caused OpenDCDiag to wake up the wrong child (always the first) when GDB backtrace support was active, which is the default. Because of that, the actual crashed child would be stuck forever in `futex_wait()` in `child_crash_handler()`:
https://github.com/opendcdiag/opendcdiag/blob/b8bdda557a388a06d66eb6a9d4455263a56e472b/framework/sysdeps/unix/child_debug.cpp#L207-L211
Additionally, we printed the backtrace in the to the first ("main") slice, which can be misleading because one might conclude it was that child that crashed.
On Windows we …
=> FW: Fix hang-on-crash for second or further slice

framework/sandstone.cpp
And in an unevaluated context anyway, due to the `sizeof` expression. Simply write what one would expect: a multiplication.
```
../framework/sandstone.cpp:1068:56: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
../framework/sandstone_p.h:507:17: note: expanded from macro 'sApp'
../framework/sandstone_p.h:75:49: note: expanded from macro 'ROUND_UP_TO_PAGE'
../framework/sandstone_p.h:74:40: note: expanded from macro 'ROUND_UP_TO'
../framework/sandstone.cpp:1068:56: note: non-constexpr function '_sApp' cannot be used in a constant expression
../framework/sandstone_p.h:507:17: note: expanded from macro 'sApp'
../framework/sandstone_p.h:500:30: note: declared here
../framework/sandstone.cpp:1068:56: warning: variable length arrays in C++ are a Clang …
```
=> FW/shmem: fix Clang warning about VLA in constexpr context

meson.build
List of added flags:
-D_FORTIFY_SOURCE=2
-z relro (release only)
-z noexecstack (release only)
-Wformat
-Wformat-security
-pie
[ChangeLog] Add Read-only Relocation, Position Independent Execution, Format String and Inexecutable Stack flags to Meson file.
=> Meson: Add multiple compilation flags

meson.build
The order was wrong: `-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2` is still setting it. That causes glibc to complain that we were using the option in non-optimised builds.
Amends f8dcbb86fb924032f835bba341bfc7965a5b06b0.
=> Meson: move setting of _FORTIFY_SOURCE=2

framework/sandstone.h
A way to supress compilation warnings on unused args added.
=> Variadic macro to overload functions/macros extended to handle 0 elements

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone.h, framework/sandstone_p.h, framework/sysdeps/unix/child_debug.cpp
This adds a `--ignore-mce-errors` option, which a) disables the `mce_check` test and b) makes the framework ignore SIGBUS errors that are related to MCEs. The Linux kernel sends those with `.si_code` equal to either `BUS_MCEERR_AO` or `BUS_MCEERR_AR`.
[ChangeLog][Framework] Added `--ignore-mce-errors` option, which will disable handling of Machine Check Exceptions. This option is useful if the user wants the tool to only react to Silent Data Errors (uncorrected MCEs are User-Observable Errors).
[ChangeLog][Framework] The --ignore-mce-errors will also cause the tool to ignore SIGBUS errors sent by the Linux kernel with signal codes indicating they were caused by MCEs. If those are detected, the test will terminate the test and mark it as skipped.
In debug builds, we also ignore SIGTRAP …
=> FW: add a way for OpenDCDiag to ignore SIGBUS relating to MCEs

.github/workflows/build.yaml, framework/sysdeps/windows/cpu_affinity.cpp, framework/sysdeps/windows/meson.build
We need to do these once in a while.
To do that, we need to stop calling `SetThreadIdealProcessorEx` because that breaks the CI.
=> CI: Upgrade the Windows build to Fedora 41

.github/workflows/build.yaml
During one of our tests under WINE, we're getting the outputs:
```
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
0690:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
```
The former is coming from libwayland-client, probably through Gtk as a dependency of WINE:
https://gitlab.freedesktop.org/wayland/wayland/-/blob/1.23.1/src/wayland-client.c?ref_type=tags#L1154-1160
The second happens when WINE attempts to launch the debugger, but there's no GUI in the CI.
Both began to be a problem with 3432e1190e343d71a516ceadedb6f31cfef62e63 (PR #587). So we now set `XDG_RUNTIME_DIR` and suppress all WINE output.
=> CI: Fix runs on Windows with WINE

.github/workflows/build.yaml, bats/sanity-check/20-selftests.bats, meson.build
The upgrade to Fedora 41 was not a good idea (PR #587). The WINE in that system is giving us trouble and I haven't been able to figure out what it was. Instead, let's run on Windows for real.
To do that, we need to switch to UCRT, because the MSVCRT-based build was having problems, like for example the `tmpfile()` function failing. Since Fedora doesn't have UCRT build packages, we have to build *on* Windows now.
I had resisted doing that because it used to take much longer to build on Windows, especially package installation, but it seems to have improved.
| Step                    | Cross-compiling | Native |
|---|---|---|
| Installing dependencies | 32 + 44 =  76 s |  182 s |
| Compilation             | 2 + 171 = 173 s |  285 s |
| Run tests               |           187 s |  100 s |
| …
=> CI: unbreak, by building and testing Windows on Windows

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone.h, framework/sandstone_p.h, framework/sandstone_tests.cpp, framework/selftest.cpp, tests/mce_check/mce_check.cpp
This is meant for tests that are production-quality, but for whatever reason we don't want to have enabled by default. If the test is explicitly named, it will get run (it won't match wildcards).
A good case for this may be an obsolete test, which may still be useful in some circumstances, like for an A-B comparison with the updated version.
=> FW: implement TEST_QUALITY_OPTIONAL

framework/sysdeps/windows/cpu_affinity.cpp, framework/sysdeps/windows/meson.build
We've already called `SetThreadGroupAffinity` with exactly one entry in the affinity mask. The only allowable processor is, by definition, the most ideal as well as the worst ideal processor.
This reverts #587's patch to cpu_affinity.cpp
=> FW/Win32: remove call to SetThreadIdealProcessor

framework/scripts/x86simd_generate.pl
The GCC feature names (for `-m` and `__attribute__((target(xxx)))`) use a dash, but the identifiers, by necessity, use an underscore. This caused the XSAVE requirement "amx-tile" to not match feature "amx_tile". The same problem would have happened for "sse4.1" and "sse4.2", but there's no XSAVE feature for those.
That caused the script to emit:
```c++
// List of features requiring XSave_AmxState
static const uint64_t XSaveReq_AmxState = 0
| cpu_feature_amx_bf16
| cpu_feature_amx_int8
| cpu_feature_amx_fp16;
```
As a result, a test that only required `amx_tile` would *not* get disabled if we couldn't enable the XSAVE state via the Linux `arch_prctl(2)` API or if the OS did not enable it with XGETBV.
Now it emits:
```c++
// List of features requiring XSave_AmxState
static const uint64_t …
```
=> FW: fix mismatch between - and _ in the AMX feature names

meson.build
GCC isn't complaining, but Clang is:
```
clang++-19: warning: -Wl,-z,relro: 'linker' input unused [-Wunused-command-line-argument]
clang++-19: warning: -Wl,-z,noexecstack: 'linker' input unused [-Wunused-command-line-argument]
clang++-19: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
```
=> Meson: silence warnings about -Wl options during compilation

framework/sandstone.cpp, framework/sandstone_p.h
This fixes running it in `--fork=no` mode, because we don't require something in `child_run()`. Moreover, it also makes the start up of tests that don't ever `reschedule()` be faster.
=> FW: initialize rescheduling on first use

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp
Because the `sApp->device_schedule` class hasn't been created in the child process.
This can be fixed by delaying the creation until `exec_mode_run()`, with some information passed to the child via the shmem block. This isn't necessary for now.
=> FW: make it clear --reschedule doesn't work in exec mode (Windows)

framework/sysdeps/unix/child_debug.cpp
This constant was added on Linux 6.6[1] to indicate a control protection fault (Intel's CET, indirect branch tracking). It is also used for ARM's GCS.
[1] torvalds/linux@a5f6c2ace9974adf92ce65dacca8126d90adabfe
=> FW/child_debug: add support for printing SEGV_CPERR

framework/sysdeps/unix/child_debug.cpp
And fix the name of interrupt 19 (SIMD Floating-Point Exception) to `#XM`. The name `XF` comes from the Linux kernel constant `X86_TRAP_XF`, but that doesn't match the Intel manual (SDM Volume 3, Chapter 7).
`#VE` is "Virtualization Exception", which we are unlikely to get.
`#CP` is "Control Protection Exception", which we can get in userspace.
=> FW/child_debug: identify #VE and #CP fault names on x86

framework/frequency_manager.hpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/sandstone_utils.h
First, include what you need. Otherwise, IDEs show everything as underlined in this file.
Second, use `AutoClosingFile` to avoid having to remember to `fclose`. This amends commit c837a1d2e52e027fbe6165cb322827248f93e708.
Finally, refer to the object indirectly in sApp. This is a 192-byte structure, which is not used by default in the majority of runs. Move it off to a pointer so we don't need to occupy space in the sApp global for the majority of users.
=> FW/frequency_manager: simple clean ups and fixes

framework/sysdeps/windows/aligned_alloc.cpp
This commit addresses an issue with builds compiled using the MinGW toolchain where the strdup function is not correctly intercepted due to the use of `_strdup` in MinGW's <string.h>. MinGW unconditionally declares `_strdup()` as `__declspec(dllimport)`, which causes calls to _strdup to bypass the custom strdup implementation.
https://github.com/mingw-w64/mingw-w64/blob/a421d2c0c68396bc342053c9348de85ecafa057e/mingw-w64-headers/crt/string.h#L67-L74
Libhwloc, a library for hardware locality, specifically calls `_strdup` instead of `strdup` for Windows compatibility. This means that simply defining `strdup` as we do for other functions in the file is insufficient, as it does not intercept `_strdup` calls. To resolve this, we fake DLL import to `_strdup` that points back to the custom …
=> FW:Fix _strdup Interception for MinGW Builds

framework/selftest.cpp
Some compilers didn't like this "+gv" constraint:
```
selftest.cpp:937:13: error: impossible constraint in 'asm'
937 |             __asm__ ("" : "+gv" (a_variable));
|             ^~~~~~~
```
But we don't need the "v" here because we know `a_variable` is an integer, therefore can only be stored in a general purpose register and "g" is slightly more general-purpose than "r":
```
‘g’
Any register, memory or immediate integer operand is allowed,
except for registers that are not general registers.
...
‘r’
A register operand is allowed provided that it is in a general
register.
```
https://gcc.gnu.org/onlinedocs/gcc/Simple-Constraints.html
Also add the `volatile` marker, otherwise the compiler eliminates because we didn't use the result of the statement.
=> Selftests: Fix build: impossible constraint

framework/meson.build
For example, if included as subproject or subdirectory into another project.
The including project may get the `gitid.h` overridden.
=> BUILD: do not generate gitid.h if not the main project.

framework/sandstone_context_dump.cpp, framework/sandstone_context_dump.h, framework/selftest.cpp, framework/sysdeps/linux/kvm.c
This completes the removal of `FILE *` in the API. This allowed for a much more easier inclusion of the CPU register context in kvm.c.
=> FW/ContextDump: update the C API to return a buffer

bats/sanity-check/20-selftests.bats
Slicing would not separate threads from the same core into different slices. When running the test on real hardware (and topology), -n2 and --max-cores-per-slice=1 do not result in two separate slices and the test will not find the main thread for the second slice in the output and, thus, will fail. --cpuset=t0 ensures that only 1 thread from a core is taken and will work if the topology has more than one core.
=> Self tests: Run with threads from two different cores.

framework/sysdeps/linux/kvm.c
Otherwise Linux kernel refuses to set them. This workarounds the issue of the initialization failing on systems with AMX hardware support.
=> KVM: do not set AMX bits in XCRS0.

framework/sysdeps/linux/kvm.c
The kernel doesn't like that:
```c
static int kvm_vcpu_ioctl_x86_set_xcrs(struct kvm_vcpu *vcpu,
struct kvm_xcrs *guest_xcrs)
{
int i, r = 0;
if (!boot_cpu_has(X86_FEATURE_XSAVE))
return -EINVAL;
```
This change is a no-op for our regular `-march=haswell` build because AVX requires XSAVE.
=> FW/KVM: don't try to set XCRS on systems without XSAVE

framework/forkfd/forkfd_c11.h, framework/sysdeps/linux/msr.c, framework/sysdeps/unix/tmpfile.c
`ATOMIC_VAR_INIT` macro was removed in C23 standard, so best to stop using it to future-proof the codebase.
Folks are free to check C23 hygiene by configuring with:
```sh
meson setup -Dc_std=gnu23 <...>
```
I'd be more than happy to squash these commits.
=> C23 hygiene: FW sysdeps, forkfd: stop using obsolete ATOMIC_VAR_INIT macro

framework/logging.cpp, framework/sandstone.h
There are multiple reasons one may want to remove or make obsolete an existing content.
This commit purpose is to give means to developer to leave message for the user to explain what happened to the test.
We can not rely on release notes on this matter.
Making the obsolete test quality to `SKIP` is not an answer either as we do not leave any message when skipping due to test quality.
[ChangeLog] Added new runtime skip category called `TestObsolete`.
=> Framework: Add `TestObsolete` skip category.

framework/sandstone.h
The old repository said
> When a replacement macro is defined, we'll suppress the test description and test groups too.
But I didn't write in the commit message why I wanted to suppress them. This is now causing problems for the tests that rely on the group's `group_init` doing something, like detecting whether certain functionality is possible or not (e.g., SELinux enforcing no SMC).
=> FW: Do allow test groups for obfuscate-test-name mode

framework/sandstone_asm.h
Unnecessary 4 bytes. But also align our payloads.
=> FW/KVM: disable the CET endbr64 instruction for ASM blocks

framework/sandstone_tests.cpp
In that mode, there is no `--list-groups` or `--enable` option to select test by group names, so there's no point in having this map populated. This fixes a crash on start of Intel's DCDiag tool, introduced by commit 4195782b31d10195942b43c3fe7c03fcaec3ac04:
```
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex-base.S:81
#1  0x000000000046610f in std::char_traits<char>::length (__s=0x0) at /usr/local/include/c++/14/bits/char_traits.h:391
#2  0x0000000000467e3c in std::basic_string_view<char, std::char_traits<char> >::basic_string_view (this=0x7fffffffdef0, __str=0x0)
at /usr/local/include/c++/14/string_view:141
#3  0x00000000004a40ae in SandstoneTestSet::load_all_tests (this=0x5d4f4d0) at ../opendcdiag/framework/sandstone_tests.cpp:40
#4  0x00000000004a447f in …
```
=> FW: don't populate the all_group_map in restricted cmdline mode

framework/sandstone_tests.cpp
The change in https://github.com/opendcdiag/opendcdiag/pull/631 was too excessive. This resulted in test failures with exit error: `EX_DATAERR`
We hit it in `exec_mode_run`
See: `if (tests_to_run.size() != 1) return EX_DATAERR;`
The affected build was Windows build but not Linux.
=> Fix: Populate all_tests but not all_group_map.

framework/meson.build
Isn't that what the name implies?
```
framework/meson.build:80: DEPRECATION: configuration_data.set10 with number. The `set10` method should only be used with booleans
framework/meson.build:81: DEPRECATION: configuration_data.set10 with number. The `set10` method should only be used with booleans
framework/meson.build:82: DEPRECATION: configuration_data.set10 with number. The `set10` method should only be used with booleans
```
=> Meson: fix warning about using set01() with value 0

framework/sandstone_tests.cpp
Without a full command-line, one can't select tests to enable or disable, nor provide a new test list with the list of tests to enable. So help the compiler by removing the code paths.
=> FW: remove unreachable code in sandstone_tests.cpp in restricted cmdline

framework/sandstone.cpp
When we're not producing a log file, we don't need the descriptions. This is the operating mode for Intel DCDiag.
=> FW: don't require test descriptions if we're not logging

framework/sandstone.cpp
This reverts commit bcb56fc858d28c08da11a9730497e46c57f607d7.
The change being reverted has an unintended consequence of increasing runtime for the tests that specify .fracture_loop_count = -1 (no fracture) and not honoring command-line-specified --max-test-loop-count value. While exactly the intention of the previous change, it is unacceptable to have the test hard-coded, unflexible logic. Thus reverting it back. The tests must honor --max-test-loop-count on the command-line if they can.
=> Revert "FW: reorganize current_max_loop_count assignment"

framework/meson.build, meson.build, tests/meson.build
We don't need warnings from system headers.
=> Meson: set dependencies' includes to "system"

framework/sandstone.cpp, framework/topology.cpp, framework/topology.h
This was the objective all along when I wrote this code in 2023, but we didn't have the information populated to achieve it. Therefore, it only made a token attempt by checking if the core count in the package was a multiple of 24 and by trying to keep things as a multiple of 4. This is no longer needed.
Instead, the rules now are:
1. (unchanged) if we have 32 cores are under test or less, then no slicing happens, otherwise we slice at the package/socket level
2. (unchanged) if the package has 32 cores or less, the `isolate_socket` mode equals `heuristic`
3. otherwise, we split at the NUMA node boundaries
4. if the NUMA node has more than 32 cores, we subdivide again on roughly equally-sized slices
5. we keep all cores and threads of a given module inside of one slice
Keeping rules 1 and …
=> FW: update the test planning to take modules and NUMA nodes into account

bats/sanity-check/20-selftests.bats, bats/yamltest.py, framework/topology.cpp
The topology/cluster_id file is always present (on x86), but it may contain -1. See `parse_topology()`[1] for where it gets first initialized. Includes test to ensure this works.
[1] https://codebrowser.dev/linux/linux/arch/x86/kernel/cpu/topology_common.c.html#parse_topology
=> FW/Topology: fix extracting the module_id when Linux doesn't know either

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone_ssl.cpp, framework/sandstone_ssl.h
One important engine or provider is the one for Intel's QAT, so it's important to know if it is being enabled. On my regular laptop, this now prints:
```
os: Linux 6.14.6-1-default
runtime: glibc 2.41
openssl: { version: OpenSSL 3.5.0 8 Apr 2025, providers: ['default 3.5.0','sandstone-rand'], engines: ['dynamic','rdrand'] }
```
=> FW/SSL: include the engines and providers in the header

bats/sanity-check/20-selftests.bats
Otherwise, we may fail to split the two cores into different slices because they are considered part of the same module.
=> CI: use packages for the mock topology for the multi-slice-crash

framework/topology.cpp
Like we do for real topologies when `module_id`s are not known, otherwise every core ends up in the same module and we will never split them.
Setting the IDs is a task for the future
=> FW/Topology (fake): make the module_id match the core_id

framework/sandstone_ssl.cpp
And don't print anything if no engine is found.
=> FW/SSL: filter the "dynamic" OpenSSL engine out

bats/sanity-check/20-selftests.bats, framework/sandstone_tests.cpp
In test list files, whitespaces between terminator and duration are producing syntax error as described in #672.
These changes fix the issue by skipping the whitespaces before encountering token contents.
Fixes #672
=> FW: permit whitespaces in the test list files when specifying duration

tests/openssl/openssl_sha.cpp
Instead of assuming that all Linux builds have OpenSSL (they don't have to) and that none of non-Linux don't (they may, FreeBSD for example).
=> OpenSSL tests: use the sandstone_config.h macro

framework/sandstone_utils.h, framework/topology.cpp
This moves `auto_fd` class to sandstone_utils.h, right next to `AutoClosingFile` class, and moves the `linux_cpu_info` class into the `__linux__` block.
=> FW/Topology: reorganize helper classes from topology.cpp

framework/logging.cpp, framework/sandstone.cpp, framework/sandstone.h, framework/sandstone_p.h, framework/topology.cpp
It doesn't need to be in `struct cpu_info` for each CPU, since this can't be different (at least, for x86 CPUs). This now creates a `HardwareInfo` global in `sApp` that we can use to populate other hardware info, for when we have them.
=> FW: move the family/model/stepping to a global

framework/meson.build, meson.build, tests/meson.build
This partially reverts commit 1cbbaf151c202f13de4ddfac342444d5975a30bc.
Unfortunately, Meson is too stupid to realise it should not pass `-isystem` for /usr/include if pkg-config reported it. That causes GCC to reorder the system includes, which in turn causes build errors:
```
cstdlib:75:15: fatal error: stdlib.h: No such file or directory
```
I've found that Boost, zlib, and Zstandard tend to have their headers directly in /usr/include. Other dependencies are less likely, so I've kept system mode for Eigen, which is what was generating warnings. Hopefully we can get away with it.
=> Partially revert "Meson: set dependencies' includes to "system""

framework/sandstone.h, framework/selftest.cpp
This field was used by the old "sliding window slicing" functionality of the OpenDCDiag framework, which was removed in commit 8f59e10b04ad82724d3bf2975d827f0aeb1ca022 (PR #271).
It is superseded by the new "parallel slicing" feature, which is enabled by the `test_schedule_*` flags to the `struct test::flags` field (introduced in commit 0f218f5b872a1b1062641ba19c8ebf1c47c92c44 PR #353).
=> FW: remove the struct test::max_threads field

framework/sandstone.cpp
I had the right idea in e6e413b3621b649173f3e25568739c42c9da9d61, but didn't look into what the SDE/pin tools already supported. It turns out they do support something.
With debug symbols active, one can dump the assembly of a given test using:
```sh
/opt/intel/bin/sde64 -debugtrace -start_address test_start -stop_address test_end -- ./opendcdiag -fno -n1 --quick -e testname
```
Without them, you can now do:
```sh
/opt/intel/bin/sde64 -debugtrace -start_ssc_mark 53 -stop_ssc_mark 45 -- ./opendcdiag ...
```
=> FW: use the SSC marker sequence instead of cmpxchg

bats/yamltest.py, framework/logging.cpp
If you run with `--disable=*` or an empty test list, we don't need the YAML line:
```yaml
tests:
```
This is not an empty array, but a null value. So instead just don't print anything. We do that by moving it from `logging_print_header()` to `logging_init()`.
=> FW/Logging/YAML: print "tests:" only if a test is executed

framework/sandstone_asm.h
Amends 793c871838bff777da99d84c750675b970d80d4c. This is producing warnings for builds without CET enabled:
```
sandstone_asm.h:20:129: warning: ‘nocf_check’ attribute ignored. Use ‘-fcf-protection’ option to enable it [-Wattributes]
```
=> FW: remove 'nocf_check' attribute from ASM functions

bats/sanity-check/20-selftests.bats, framework/logging.cpp, framework/sandstone.cpp, framework/sandstone_p.h, framework/selftest.cpp
For more complex tests, it's possible that some nested function sets the state but fails to notify the outer functions that they did. If the callback function returned with `EXIT_SUCCESS`, we may end up not noticing the state had changed. We already handled some cases, but not all of them:
| Function \ Stage | init | run | cleanup |
| --- | --- | --- | --- |
| `log_skip()` | ✘ | ✔* | ✘ |
| `log_error()` | ✔ | ✔ | ✘ |
| `report_fail_msg()` / `memcmp_or_fail()` | N/A | ✔ | N/A |
(*) Probably didn't work if running in no-output logging mode.
This PR fixes the issue by storing whether the test has skipped, which is done by using a negative `fail_time`. It also changes the non-fail case to store zero there to simplify the cleaning up of the shared memory area between tests.
Drive-by fix …
=> FW: ensure we handle tests that log_xxx() but EXIT_SUCCESS in their init()/run()/cleanup()

meson.build
GitHub-hosted Actions OS images, namely `ubuntu-latest`, is based on 24.04 today. In that distro, the version of meson is v1.3.x. With that version, you can specify the C++23 language standard. But, C23 is not an option yet.
I wanted to bump c_std=gnu23 as well, but that's not introduced until v1.4, so I'll wait until hosted runners get upgraded.
=> meson: bump minimum to v1.3, cpp_std=gnu++23

framework/device/cpu/topology.cpp
It's UB to do `1 << 32` and that will in any case never match `0x1'0000'0000`.
Amends commit f74847bb1a9434621803239ee09b77597c15990b from nearly 2 years ago.
=> FW/Topology/Win32: fix bug for affinity masks bits set above 32nd

framework/device/cpu/topology.cpp
Amends commit 41a6995874eb504fef18f259ad4b8ed4a4dda830, which refactored the Windows code and made us call the Win32 API in spite of getting information from CPUID. We don't need it for the processors' information if CPUID works, only for NUMA.
=> FW/Topology/Win32: don't use GetLogicalProcessorInformationEx if CPUID works

framework/device/cpu/topology.cpp
The documentation for `GetLogicalProcessorInformationEx()`[1] is vague on what gets returned. It says:
> Requests for `RelationNumaNodeEx` or `RelationAll` will return
> `NUMA_NODE_RELATIONSHIP` structures that contain an array of affinities
> for the node over all groups.
But doesn't explain that the `Relationship` member will still contain `RelationNumaNode`. Testing on my workstation (Windows 11) and on a Windows 2022 server shows that Windows returns `RelationNumaNode` with a non-zero `GroupCount`.
After this, the `cpu_info::numa_id` field gets populated. Testing on the server with multiple sockets confirms it:
```yaml
command-line: 'opendcdiag.exe --disable=* -Y -o - --cpuset=c0'
version: opendcdiag-479c4adea2e1
os: Windows Server v10.0.20348
runtime: UCRT
openssl: null
timing: { …
```
=> FW/Topology/Win32: also handle `RelationNumaNode`

framework/device/cpu/topology.cpp
We always initialise for `Logical`, `Core`, and `Package` if either CPUID leaf works, but not `Module`. That causes erroneous behaviour (EB) in `detect_topology_via_cpuid`.
=> FW/Topology: initialise `topology_widths_array`

framework/sandstone.cpp
The tool says that use of `auto` causes a copy here. That's correct and `collate_test_groups()::Group` has a `std::vector` member.
=> FW: fix performance issue found by static analysis tool

framework/device/cpu/topology.cpp
Lock the mutex at the beggining of the method finish_reschedule() to avoid data race condition. This problem was flagged by static code analysis tool.
=> FW/Reschedule Barrier: Fix race condition on finish_reschedule

framework/device/cpu/cpu_device.h, framework/logging.cpp, framework/random.cpp, framework/sandstone_p.h, framework/sandstone_unittests_utils.cpp, tests/ifs/unit/ifs_unittests.cpp
Other devices would introduce their own struct representing a device (GPU)
=> CPU-separation: use `device_info` alias in common code

bats/sanity-check/20-selftests.bats, framework/sysdeps/unix/child_debug.cpp
Fixes commit f1d4860465f228bc9e60c856eeefc86018339bb5, which made this use `std::string`: it opens a temporary file (memfd on Linux) for the child process and then reads from it. But a temporary file is not a pipe and the child process will sync its read/write position with the the parent. Therefore, we must `lseek()` prior to reading from the fd.
And of course we must add the number of bytes read to `total_read`.
=> FW/Logging: fix capturing of ps output on Linux for hung tests

bats/sanity-check/21-slicing.bats
I don't know how this passed before, but I forgot the `sandstone_yq` shell function passes the tool's output to its stdout, so Bats would log it. That is fine when running in the `@test` but not if we are trying to capture another shell function's output.
We were getting a very cryptic
```
opendcdiag/bats/sanity-check/21-slicing.bats: line 123: set: --: invalid option
```
Because the output of the `cpuset_two_modules` function was:
```
--- THIS IS AN UNOPTIMIZED BUILD: DON'T TRUST TEST TIMING! command-line: 'opendcdiag --on-crash=core --on-hang=kill -Y -o - --cpuset=t0 --disable=*' ...
```
Additionally, use make the third test function use the same shell function, since all we need are unique modules anyway.
=> CI/Bats: redirect output of the yq run to /dev/null

bats/sanity-check/21-slicing.bats, framework/sandstone.cpp
There was an off-by-one error between the test and the plan, observed on an 86-core Intel Xeon 6P: the 172 threads become 172 "packages" in debug mode, which should produce 6 slices. However, because we rounded the `slice_size` down to 28 instead of 29, that added a 7th slice.
=> FW: update the "dumb" test plan to round up

framework/selftest.cpp
Clang assumes some pre-optimizations for some compile-time conditions. One of these are extremely large allocations. As the framework overrides default implementation, one of the tests (selftest_malloc_fail) doesn't work as expected. The optimization must be forced out in this particular case.
=> Prevent clang "built-in" malloc() optimization

framework/device/cpu/topology.cpp, framework/device/cpu/topology_cpu.h, framework/sandstone.cpp, framework/sandstone_opts.cpp, framework/sandstone_p.h, framework/selftest.cpp, framework/topology.h
Actor, not a state.
---------
- parent: https://github.com/opendcdiag/opendcdiag/pull/736
=> FW: rename rescheduler class and objects

framework/sandstone.cpp, framework/sandstone.h
It was a mistake to remove it in the first place.
=> FW: provide C-based interface for reschedule

tests/meson.build
The -Dmarch_base= config option sets a minimum CPU for the whole build. So far, we've only used "westmere" (a.k.a. "x86-64-v2") and "haswell" (a.k.a. "x86-64-v3"), which was ok. But if someone used a later version like "x86-64-v4" or "diamondrapids", some or all of the tests would downgrade to a lesser CPU.
=> Tests/x86: don't downgrade CPU target from what the user asked

bats/sanity-check/20-selftests.bats
Because our code does handle the empty case:
```c++
if (const char *env = getenv("PATH"); env && *env)
path = env;
else
path = _PATH_DEFPATH;
```
In which case we may have found GDB when we didn't mean to. Don't ask me how this is passing in the CI. Of course, now that I've shown it shouldn't be, it'll prompty break everywhere[1].
And set it for a single command, instead of setting it in the shell and making our lives harder in using shell tools.
[1] https://en.wikipedia.org/wiki/Schr%C3%B6dinbug
=> CI/Bats: set PATH to something non-empty and for a single command.

framework/device/cpu/cpuid_internal.h
Because `exit()` will run static destructors, which may have code compiled for later CPU generations and thus crash.
I noticed this when trying to run a build designed for the upcoming Diamond Rapids processor (APX-F + AVX10.2):
```
./opendcdiag --version
This application requires certain features not found in your CPU: sha waitpkg gfni vaes vpclmulqdq movdiri movdir64b uintr serialize pconfig sha512 avxvnni cmpccxadd avxifma avxvnniint8 avxneconvert avxvnniint16 apx-f
exit: invalid
zsh: illegal hardware instruction (core dumped)
```
GDB said:
```
Program received signal SIGILL, Illegal instruction.
0x00000000004c1c20 in ?? ()
(gdb) bt
#0  0x00000000004c1c20 in ?? ()
#1  0x00007ffff7fc9c92 in _dl_call_fini () at dl-call_fini.c:43
#2  0x00007ffff7fcced4 in _dl_fini () at dl-fini.c:120
#3 …
```
=> FW/CPU: exit with `_exit()` when the CPU check fails

tests/meson.build
Client CPUs with AVX512 don't have it, such as my Tiger Lake laptop and a lot of other systems where the kernel or BIOS disables TSX due to the TSX Async Abort (TAA) mitigation.
```yaml
tests:
- test: eigen_svd_cdouble
details: { quality: production, description: "Eigen SVD (Singular Value Decomposition) solving payload, which issues a bunch of matrix multiplies underneath, now operating on std::complex<double>" }
state: { seed: 'LCG:570756152', iteration: 0, retry: false }
time-at-start: { elapsed:      0.000, now: !!timestamp '2025-09-05T22:52:46Z' }
result: skip
skip-category: CpuNotSupported
skip-reason: 'test requires rtm'
time-at-end:   { elapsed:      0.000, now: !!timestamp '2025-09-05T22:52:46Z' }
test-runtime: 0.036
```
Amends commit 379d52b0c5223004eae599633e6b5a2a4eefc4d5, …
=> Tests/x86: remove `-mrtm` from the AVX2 & AVX512 builds

framework/logging.cpp
Amends commit 3994e19308d9b170ee5d62514d27234d368efccc, which introduced this problem by opening "/dev/null" with `O_CLOEXEC`. I don't think this affected Windows because the three standard handles are special.
=> FW/Logging: fix unexpected closing of stdout in `-fexec` mode

framework/device/cpu/logging_cpu.cpp, framework/device/cpu/logging_cpu.h, framework/device/cpu/meson.build, framework/logging.cpp, framework/logging.h
This includes moving Tap and KeyValue loggers as cpu-only.
Inheritance order is changed, and now both Tap and KeyValue inherit
from Yaml.
=> CPU-separation: extract device-specific code from `logging.cpp`

bats/sanity-check/20-selftests.bats, framework/sandstone.cpp, framework/sandstone_tests.h, framework/selftest.cpp
This is how it was meant to be, how it was designed back in day (commit 7c2b9cd8cc03828503da1526825dc5944ad1a3b6 in the internal repository prior to open-sourcing), but was lost in refactoring with PR #495 (commit 7c2b9cd8cc03828503da1526825dc5944ad1a3b6).
This new design is stricter in that the preinit function can only affect things that the parent process will see, for example, the timing and looping constraints or replacing the init function (so long as it runs in the parent).
No self-test for group inits because in the current design doesn't allow the selftests to have group init, therefore we can't test the side- effect.
=> FW/Test: preinit the tests in the main process

framework/sandstone_opts.cpp, framework/sandstone_p.h
Unless we plan to use it in future.
Fixes #586
=> FW: remove dead option `--mce-check-every`

framework/fp_vectors/Floats.h
In contrived code where framework FP types are used-- by including fp_vector/Floats.h-- said code will not compile due to a missing FLT_MANT_DIG macro. The cfloat header has that macro.
Contrived code (referenced as `xyz.cpp`) used:
```
#include <array>
#include <bit>
#include <print>
#include <stdfloat>
#include <fp_vectors/Floats.h>
int main(int, char**)
{
static const std::array<BFloat16, 2> arr { BFloat16 {1, 0x78, 0}, {0, 0x78, 0} };
for (const auto& val : arr)
std::println("{}", std::bit_cast<std::bfloat16_t>(val));
return 0;
}
```
Compiled from top-level of checkout using:
```
g++ -Iframework -std=gnu++23 -pipe -o xyz xyz.cpp
```
=> FW/Floats: add missing header for contrived compilation

framework/interrupt_monitor.hpp, framework/sandstone.cpp, framework/sandstone_p.h, tests/mce_check/mce_check.cpp, tests/smi_count/smi_count.cpp
There seems to be no need to pollute `SandstoneApplication`'s interface with
MCE related stuff.
=> FW: decouple `InterruptMonitor` and `SandstoneApplication`

bats/sanity-check/29-kvm.bats
This tests all three run modes: -fno, -fexec (default on Windows), and -fyes (default elsewhere). This is extra pedantic, because of course we can't test the Linux KVM API on Windows, just in case in the future someone adds an equivalent way to test on other OSes.
=> CI/Bats: add tests to ensure the KVM tests do run without crashing

framework/sandstone_test_groups.cpp
=> FW: remove redundant `extern` keyword in test groups definitions

framework/device/cpu/test_data_cpu.h, framework/device/test_data_device.h, framework/sandstone_p.h, framework/test_data.h
Put common stuff in common code, and the rest inside cpu-specific file. For cpu it's only `effective_freq_mhz`
=> CPU-separation: isolate `PerThreadData`

framework/device/cpu/cpu_device.cpp, framework/device/cpu/cpu_device.h, framework/device/cpu/cpuid_internal.h, framework/device/cpu/premain.cpp, framework/device/cpu/scripts/x86simd_generate.pl, framework/sandstone.cpp, framework/sandstone.h, framework/scripts/generate_test_list.py
This commit also brings back definition of `device_features` (former `cpu_features`) variable back to the common code.
=> CPU-separation: use universal name `device_features_t`
