- framework/selftest.cpp
All the tests so far were #PF. The easiest way to cause a #GP is with a
non-canonical address.
Log:
```yaml
- { level: error, text: 'E> Received signal 11 (Segmentation fault) code=128 (SI_KERNEL), RIP = 0x44e2c7, CR2 = (nil), trap=13 (GP), error_code = 0x0' }
- level: warning
text: |1
W> #4  0x000000000044e2c7 in cause_sigsegv_noncanonical () at ../../../src/arkose/arkose-one/opendcdiag/framework/selftest.cpp:429
429          asm volatile ("movl (%1), %0" : "=r" (result) : "r" (ptr));
=> 0x44e2c7 <cause_sigsegv_noncanonical()+42>:   mov    (%rax),%eax
- level: info
text: |1
Registers:
rax   = 0x8000000000000111
```
> FW/Unix: add a SIGSEGV test for #GP

- .github/scripts/check-git-history.sh
- .github/workflows/pr.yaml
Check that:
1. No merge commits on the branch being merged;
2. Each non-merge commit has Signed-off-by clause.
> CI: git checks

- framework/topology.cpp
This code used to violate DRY (Don't Repeat Yourself).
> FW/topology: rewrite the system info detection with a template

- framework/selftest.cpp
So we can add the attribute to tell ASan not to do anything about them.
Also removes inline assembly, which has to be a good thing, right?
> FW/selftests: move the actual, evil crashes into specialised functions

- framework/random.cpp
We currently always enable the AESNI instructions, but it need not be
always the case.
> FW/random: make the AES PRNG engine optional

- framework/meson.build
- framework/sysdeps/linux/interrupt_monitor.cpp
- meson.build
Instead of depending on whatever got passed to the compiler with with
-I options.
> FW/linux: #include the extra files with full path

- framework/topology.cpp
Added PPIN support from /sys on Linux.
Made parsing of /proc/cpuinfo happen only once.
> FW/topology: improvements to PPIN and microcode obtention code

- framework/scripts/x86simd_generate.pl
- framework/simd-amd.conf
- framework/simd.conf
Quite a few minor fixes after attempting to submit this to Qt, at https://codereview.qt-project.org/c/qt/qtbase/+/392833.
Also added the file with AMD-defined intrinsics, though it's unused in our build.
> Updates to simd.conf

- meson.build
> Meson: remove duplicated output

- tests/ifs/ifs.c
- tests/meson.build
For more info, See: https://lwn.net/Articles/886510/
> In-field Scan: CPU online self-test support.

- framework/sandstone.cpp
- framework/sandstone_p.h
- framework/selftest.cpp
> framework: Fix timeout calculation when --timeout flag is set.

- framework/simd.conf
> FW simd: Add clflush to cpu_features

- framework/sysdeps/unix/child_debug.cpp
Running it ensures that it can be launched, but it's overkill and
underkill at the same time. It's overkill because its launch procedure
is quite expensive, loading Python libraries and all. But at the same
time, it doesn't tell us that it can actually debug our process, for
some esoteric reason.
So instead just check that the executable exists in PATH and has the
necessary +x bit. The access(2) system call is very cheap.
> FW: don't execute gdb to find out if GDB is present

- framework/sandstone.cpp
This partially reverts commit 0bbb15f7922da7d78b881507ec1d7cac916182e5,
by ensuring that the user code in the test->init() function is run in a
predictable logical processor. Since our abstraction doesn't allow us to
save and restore the ambient affinity state, just create a thread that
we can then pin (the Windows implementation is defective due to
limitations of the processor group API).
On my 4-core x 2-thread system, strace reports these sched_setaffinity()
calls on Linux, when I run:
taskset -c 1,4,6,7 ./opendcdiag --selftests -e selftest_logs_options --disable=mce_check
```
sched_setaffinity(0, 8, [1, 4, 6, 7])   = 0
[pid 454934] sched_setaffinity(0, 128, [1]) = 0
[pid 454934] sched_setaffinity(0, 128, [4]) = 0
[pid 454934] sched_setaffinity(0, 128, [6]) = 0
[pid 454934] …
```
> FW: Pin the thread that runs the tests' init() function

- .editorconfig
- framework/meson.build
- framework/sysdeps/darwin/meson.build
- framework/sysdeps/freebsd/meson.build
- framework/sysdeps/linux/meson.build
- framework/sysdeps/unix/meson.build
- meson.build
- tests/meson.build
Finally getting around to twitchy changes that have been bothering me for some time. 😆
> meson: some nit-picky cleanups

- framework/cpuid_internal.h
- framework/logging.cpp
- framework/meson.build
- framework/sandstone.cpp
- framework/sandstone_config.h.in
- framework/sandstone_p.h
- framework/test_knobs.cpp
WIP. Not ready for prime time just yet, so hold off reviewing for now.
Putting this up so folks get the gist of what I'm trying to do. Yes, it fails CI, and I know why.
> prune away i18n/l10n functionality, repurpose for restricted logging scenario

- framework/fp_vectors/Floats.h
- framework/meson.build
- framework/sandstone_config.h.in
- framework/sandstone_data.h
- framework/sandstone_p.h
- framework/sandstone_utils.cpp
- framework/sysdeps/unix/meson.build
Use sandstone_config.h more extensively.
> Meson config updates

- framework/logging.cpp
- framework/meson.build
- framework/sandstone_chrono.cpp
- framework/sandstone_chrono.h
- framework/sandstone_p.h
- framework/sandstone_utils.cpp
- framework/sandstone_utils.h
- framework/sysdeps/linux/effective_cpu_freq.hpp
- framework/test_selectors/ListFileSelector.h
- framework/unit-tests/sandstone_utils_tests.cpp
This reorganises some files out of the kitchen sink ("utils.h"), plus it improves `string_to_milliseconds`.
> sandstone_chrono: create and improve

- framework/sandstone.cpp
This also updates the background scan to wait if the last test failed (though usually background scans are run with `--fatal-errors`).
> Reorganise the main loop, like we had been asking for

- framework/sandstone.cpp
- framework/sandstone_p.h
If someone wants to add specific branding or a copyright notice.
> FW: add print_application_{banner,footer}()

- bats/sanity-check/20-selftests.bats
To prevent a silly regression like what happened in PR #116 (commit @d0d1227e609c7e4a779a3d64775aa67d6f0605a2).
> bats: add a test for --test-file-list

- .github/workflows/build.yaml
> CI: Fix openssl package name

- framework/meson.build
- framework/sandstone_ssl.cpp
> FW: remove openssl version restriction

- framework/sysdeps/linux/effective_cpu_freq.hpp
The coarse clock can return the same time twice:
```
(gdb) p before.ts
$1 = {tv_sec = 4093053, tv_nsec = 275360858}
(gdb) p after.ts
$2 = {tv_sec = 4093053, tv_nsec = 275360858}
```
Which would result in a division by zero (the other values in the structure prove that those are two different snapshots).
Additionally, save the time point in std::chrono form so we can more easily compare for equality, in case the Linux clock source did return the same value twice. Floating point divisions by zero on x86 as usually masked, so we'd get normally only get a NaN, which is why this hasn't been a problem.
[ChangeLog][Framework] Improved the precision of the calculation of the effective CPU frequency on x86.
> FW: use the non-coarse monotonic clock to calculate frequencies

- framework/main.cpp
> FW/Unix: fix fd leak in case we decide not to exec the fallback

- bats/sanity-check/20-selftests.bats
Both with --test-list-file and with -e
> CI/BATS: test that --test-list-randomize is random

- framework/simd.conf
Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>
> FW simd: Add enqcmd to simd.conf

- framework/test_selectors/ListFileSelector.h
- framework/test_selectors/TestrunSelectorBase.h
- framework/test_selectors/WeightedSelectorBase.cpp
* Remove unused virtual function
* Replace macro with explicit C++ Code
> Test selectors cleanup

- framework/sandstone.cpp
Previously, we would initialise all groups, even those for which no test had been selected.
> FW: fix apply_group_inits() to init groups on demand

- framework/logging.cpp
- framework/sandstone.h
Signed-off-by: dawid-sabat <dawid.sabat@intel.com>
> Disable printing log_data if SANDSTONE_NO_LOGGING is defined.

- tests/ifs/ifs.c
Starting from kernel 6.2, In-field Scan (aka IFS) feature will support
multiple test images that can be load and run independently between them.
IFS test would load and run one of the available images on each core.
This commit also includes interactive options:
- test_file: Specify Image ID number. If ID does not exist, default ID (0x1)
would be use. Values accepted: any unsigned integer.
- enforce_run: When previous IFS run failed, next IFS run would refuse to run,
unless enforced. Values accepted: 1
> IFS test: Add support for multiple test images

- framework/sandstone.cpp
Test runtime (defined as current_test_startime -> current_test_endtime) is calculated as close the test as possible to avoid false positives with selftests (where it is expected that the test runs not shorter than given duration). In previous time 'endtime' included framework overhead, while 'starttime' didn't, what "randomly" resulted with CI failures
> Fixed test runtime calculations.

- bats/sanity-check/20-selftests.bats
ie. match name-v123rc1-suffix123 (1234567890123456789012345678901234567890)
> bats: regex fix to match rc (release candidate) in version string.

- tests/ifs/ifs.c
- tests/ifs/sandstone_ifs.h
Improvements include:
- Automatic detection of image_support
- Let cpu 0 control execution
- More useful info on logs
> IFS: multiple workflow and log improvements

- framework/meson.build
- framework/sysdeps/darwin/meson.build
- framework/sysdeps/freebsd/meson.build
- framework/sysdeps/linux/meson.build
- framework/sysdeps/unix/meson.build
- framework/sysdeps/windows/meson.build
- meson.build
- meson_options.txt
- tests/meson.build
Get rid of tab-based indentation and use 4 spaces, consistent with the rest of the project, instead.
> Meson: Replace tabs with 4 spaces.

- framework/sandstone_test_utils.h
- framework/unit-tests/sandstone_test_utils_tests.cpp
This commit adds a structure used by tests to select from a list of possible values based on a weighted distribution.  Simply provide a map of value => weights to the constructor and call pick() to get a vlaue from the list.
```
Example:
WeightedPicker<std::string> picker({
{"value_a": 1},
{"value_b": 5},  // This value should come up 5X more
{"value_c": 0},  // This value should never come up
});
...
std::string value = picker.pick();
```
> Added WeightedPickerTestFixture to sandstone_test_utils

- framework/scripts/x86simd_generate.pl
- framework/simd.conf
Also, recognize the corresponding CPUID leaf.
> Update simd.conf: enable Sierra Forest and Grand Ridge features

- framework/sandstone.cpp
- framework/scripts/generate_test_list.py
- meson_options.txt
1. Change C array to std::span.
2. Clean up docs and code.
> Clean up and better interfaces for multi-list support.

- framework/sandstone_unittests_utils.h
- tests/eigen_sparse/eigen_sparse.cpp
- tests/ifs/ifs.c
- tests/openssl/openssl_sha.cpp
tests/eigen_sparse/eigen_sparse.cpp
tests/ifs/ifs.c
tests/openssl/openssl_sha.cpp
> Tests: Update skip reason message for the below tests:

- tests/ifs/ifs.c
- tests/ifs/unit/ifs_test_cases.h
- tests/ifs/unit/ifs_unittests.cpp
This PR includes the fix for a unittest and a fix to skip when feature is not available for running.
> IFS: multiple minor fixes

- bats/sanity-check/20-selftests.bats
In some container environments, gdb doesn't work at all. In our self-hosted runners, I'm guessing it fails to ptrace the crashing process, because there's no output from it in the log. But even when it doesn't work, on Unix and x86-64, we do have the built-in register dump, so we should be able to test that.
Meanwhile, in the hosted GitHub Actions runners, gdb hangs forever and the signal context doesn't seem to get transmitted at all to the parent process. In this case, not even the built-in register dump works.
> CI/Bats: check that gdb works instead of just checking its presence

- bats/sanity-check/20-selftests.bats
Looks like on one of our self-hosted runners, even though gdb was able to start debugging /bin/true, it still couldn't attach to the OpenDCDiag child process. So instead of trying to guess whether GDB will work, simply accept it might have failed and detect at runtime when it might have.
> CI/Bats: fix the backtrace selftest again

- bats/sanity-check/20-selftests.bats
This partially reverts commit efbb4e0c454125f3030e618190e3e0bd154abc62 (PR #238), restoring the requirement to test gdb if gdb is found to be working, but changing what we test of gdb. Instead of trying to start and run a process, we instead ask gdb to attach to a running process, which is what our child_debug.cpp does.
> CI: Partially revert "CI/Bats: fix the backtrace selftest again"

- bats/sanity-check/20-selftests.bats
Otherwise, not even the internal register dumper (available only for x86_64) will run. But GDB must be present, even if it can't attach to running processes, because OpenDCDiag doesn't like when we pass --on-crash=backtrace without gdb.
> CI/Bats: re-re-fix the backtrace test: always pass --on-crash=backtrace

- framework/logging.cpp
- framework/sandstone.cpp
Apple doesn't want to be part of the cool kids?
> FW/Mac: fix build on macOS: it doesn't consider itself Unix

- framework/logging.cpp
Not the most efficient code, but it removes the direct use of stdio.h, in preparation for its removal from logging.cpp. In any event, it's already used in logging_format_data(), the other part of `logging_report_mismatched_data()`.
> FW/logging: use std::string concatenation in log_data_common()

- bats/sanity-check/20-selftests.bats
Instead of just wishful thinking in the comments.
> CI/Bats: confirm that we didn't run selftest_pass_low_quality in code

- framework/sandstone.cpp
> FW: move the perror("fork") into call_forkfd()

- framework/sysdeps/unix/child_debug.cpp
We can do buffering on the parent process, so this avoids the huge sequence of write() system calls that you'd see on strace(1). Now you just see
```
[pid 275104] write(7</memfd:>(deleted), "Registers:\n rax   = 0x0000000000"..., 4472) = 4472
```
This is done in preparation of removing the FILE* we kept per thread.
open_memstream() was a glibc extension to POSIX, but was added to the 2008 edition, so it's available everywhere (except Windows, but this code isn't compiled there).
> FW/child_debug: use open_memstream() for the register dump FILE* stream

- bats/sanity-check/20-selftests.bats
- framework/sandstone.cpp
- framework/topology.cpp
PR #276 broke it. I now added a test to ensure it doesn't break.
> FW: Fix --cpuset parameter and revamp

- framework/topology.cpp
And we can use std::tuple's operator< to perform the comparison for us.
> FW/Topology: rewrite reorder_cpus() with a simple std::sort()

- framework/sandstone.cpp
The child no longer performs the sliding window slicing of the system, so I merged them. To match the new convention, I've also renamed child_run(), which now also matches exec_mode_run(). Logically, the combined function ought to be located above wait_for_child() in the source, but I'm not going to break git blame for this.
I want to move the CPU feature check back into the parent process to speed up the execution of such skipping tests, but that's a task for another day. It used to be in the parent but I moved it back on 2021-03-19 because of logging:
FW: move the per-test check on CPU features and timing into the child
This means we'll launch a child for tests that will be skipped, thus
adding a bit of overhead. But it simplifies logging (especially for
Windows support).
> FW: merge the run_thread_slices() and run_child() functions

- framework/meson.build
- framework/sandstone.cpp
- framework/sandstone_config.h.in
- framework/sysdeps/unix/child_debug.cpp
- meson_options.txt
More fine-grained control of the options.
> Add Meson-time config options for Triage and more fine-grained child_debug support

- bats/sanity-check/20-selftests.bats
- framework/selftest.cpp
To confirm that we got scheduled where we expected to get scheduled, we ask the OS where we are.
This doesn't work on Windows systems with more than 64 logical processors due how it divides the processors into [Processor Groups](https://learn.microsoft.com/en-us/windows/win32/procthread/processor-groups), as the number we print from the tool does not match anything meaningful in the OS above 64.
> CI/Bats: add a test to confirm that we are using the cpuset threads

- framework/sandstone.cpp
- framework/topology.cpp
- framework/topology.h
No effective changes, just moving the code around to apply the "Don't Repeat Yourself" principle and use lambdas. I've moved the code that manipulates the topology into topology.cpp, to make it more self-contained.
> FW/Triage: cleanup and reorganise the code

- framework/sandstone.cpp
> FW: Don't Repeat Yourself in run_one_test()'s marking up of failures

- framework/topology.h
Last use removed by 150a8da64ae9f65c9cefb6ecc008c1e980f7f68e (PR #327).
> FW/Topology: remove Topology::add_package()

- framework/random.cpp
> FW/Random: don't use std::stringstream for the AES engine

- framework/logging.cpp
- framework/sandstone.cpp
- framework/sandstone_p.h
We only start one child for now, but now we can wait for more than one.
> FW: rewrite wait_for_child() as wait_for_children()

- framework/simd.conf
It's bit 7, not 6, in Leaf 7 Sub-leaf 1, EAX.
> simd.conf: correct the bit for cmpccxadd

- framework/sandstone.h
Everything is now dynamically-sized.
> FW: remove MAX_THREADS macro

- tests/ifs/ifs.c
[ChangeLog][ifs_array_bist] Promote test to production.
> ifs_array_bist: Promote to production

- framework/sandstone.cpp
I added the feature to test -fexec on Linux, and clearly didn't actually use it on Windows. Commit a4bfe65d5750a8fb1707051988972be1ce6850b4 (PR #307) fixed finding it and I confirmed it did start... but didn't debug why I was getting "invalid parameter passed to C function".
It turns out that the file descriptorinheritance doesn't work through gdbserver (my guess is that the gdbserver implementation didn't use _spawnv, so the `cbReserved2` and `lpReserved2` fields of `STARTUPINFO` weren't set). That means we must pass the actual path so the child process can open the shmem.
Logging will NOT work for the same reason, but at least one can debug what's happening in the child process. It's possible the handles were inherited so it may be possible to fix this.
> FW/Win32: fix use of gdbserver on Windows

- bats/sanity-check/20-selftests.bats
- framework/logging.cpp
- framework/selftest.cpp
- framework/test_knobs.cpp
- framework/test_knobs.h
- framework/unit-tests/test_knob_tests.cpp
This PR adds support for floating point knob values
> Added support for floating point knob values

- framework/meson.build
- framework/sandstone.cpp
- framework/sandstone_ssl.h
- framework/sandstone_ssl_rand.cpp
- framework/sandstone_ssl_rand.h
> sandstone_ssl: Add our own random generator

- framework/sandstone.cpp
Our `mmap()` replacement doesn't set errno properly for everything, leading to:
```
internal error: could not map the shared memory file to memory: No error
```
Now we get:
```
internal error: could not map the shared memory file to memory: Access is denied.
```
> FW/SharedMemory: print proper error messages on Windows

- framework/sysdeps/linux/kvm.c
This commit will handle the KVM_EXIT_FAIL_ENTRY case explicitly with a separate log message which gives a description from the hardware of why VM-Entry failed.
> FW/sysdeps: Handle all KVM_EXIT_* scenarios

- framework/sysdeps/linux/kvm.c
Add explicit KVM_EXIT_* enums and kvm_run union structures to kvm.c that are not supported in older kvm.h header file.
This should handle all KVM_EXIT_* scenarios on both old and new versions of kvm.h header file.
> FW/sysdeps: Fix some KVM_EXIT_* scenarios

- framework/sandstone.cpp
Commit 7cf55b1999c6425670f3b0d7eaf16b0a077023d3 changed it so we'd pass a file name instead of a file descriptor and I am sure I tested this, but something must have changed and now I'm getting "Permission denied" when trying to open the tempfile.
But passing handles does work, as speculated in that commit message, so let's do that.
> FW/Win32: re-fix use of gdbserver

- framework/sandstone.h
- framework/sandstone_chrono.cpp
- framework/sandstone_chrono.h
- framework/unit-tests/sandstone_utils_tests.cpp
to allow "profiling" the tests from the code (without additional instrumentation).
> C-functions to measure the time (user/sys/wallclock)

- framework/random.cpp
This allows the AES engine to be enabled even if the target compilation options do not include AES. We'll compile the code but only run it if the AESNI instructions are detected at runtime.
Also include a few fixes for the handling of the `-s` option when passed a file. If it weren't at least that big, the error messages the tool printed were misleading:
```
$ echo a > /tmp/seed
$ ./opendcdiag -n1 -s /tmp/seed
read: No such file or directory
```
A case of "Not a typewriter"[1]. Now you get:
```
./opendcdiag: could not read from /tmp/seed: File too short
```
[1] https://en.wikipedia.org/wiki/Not_a_typewriter
> FW/Random: make the AES engine optional and detected at runtime

- framework/sandstone_test_utils.h
> Covertiy: Fix CID 652556 COPY_INSTEAD_OF_MOVE

- framework/frequency_manager.hpp
This commit initializes the member variables in the FrequencyManager.
> Uninitialized scalar field

- framework/meson.build
- framework/sandstone_config.h.in
- meson_options.txt
> FW: Remove the old "SANDSTONE_GA" macros

- framework/sandstone_ssl.h
- Adding EVP hash related functions to fetch operations from providers.
Signed-off-by: Alex V Jaramillo <alex.v.jaramillo@intel.com>
> Enabling EVP hash APIs

- framework/sandstone.cpp
- framework/scripts/generate_test_list.py
It's logged as a comment only for now...
> FW/Tests: log the name of the test list we used

- framework/logging.cpp
It's often useful to get the full buffers for debugging, because either you need to interpret the data that came before to make sense of what you're seeing or because you want to see if more errors have shown up.
This removes the hardcoded 64 from the source file. The default value of --max-logdata is 128, which this commit does not change behaviour of the defaults.
[ChangeLog][Framework] The --max-logdata option now also controls the memory dumps when memory miscompares are detected. In particular, --max-logdata=0 causes the full blocks that failed to compare to be printed.
> FW/Logging: obey --max-logdata for the memcmp_or_fail mem dump

- .github/workflows/build.yaml
Less duplication. Could do it for Windows, but it's a bigger hurdle.
> CI: Merge the GCC and Clang steps together

- framework/frequency_manager.hpp
Older version exits the framework with error message if `userspace` is not present in sysfs file `/sys/devices/system/cpu/cpu%/cpufreq/scaling_available_governors`.
In this version, the framework will enable `userspace` if not present and set the system back to it's original state at the end.
> FW/Frequency Manager: Handle "userspace" not present scenario

- framework/sysdeps/windows/child_debug.cpp
I tested and it works. I'd like to expand it to have more functionality like the Unix version, but that's a job for a later time.
> FW/Win32: add --on-hang=gdb

- framework/logging.cpp
- framework/sandstone.cpp
- framework/sandstone_p.h
Available in -vvv output or in case of hang.
> FW/Win32: add some more process-summary information

- bats/sanity-check/20-selftests.bats
- framework/sandstone.cpp
- framework/selftest.cpp
In `signals_init_child()`, we call `setsid()`, so each direct child we start is in its own process group and session, whose IDs match the child PID. We do that so the main process gets Ctrl+C from the terminal, and all it did was relay that to each child.
This commit makes the Unix version instead relay to each child's process group. That way, if a child forks and has children of its own, all those children will get the signal too. The unit tests I added or modified confirm that the grandchildren die in both timeout and the signal cases (Ctrl+C/SIGINT, SIGTERM, SIGHUP).
> FW/Unix: kill the children using their PGID, not PID

- CODE_OF_CONDUCT.md
Kent is no longer working with us, so update to Arzhan and me (two people, in case the report needs to be about the other).
> Docs: update CODE_OF_CONDUCT enforcement email addresses

- .github/workflows/build.yaml
- docs/coding_style_guide.md
- docs/writing_tests.md
- framework/frequency_manager.hpp
- framework/sandstone.cpp
- framework/topology.cpp
- tests/examples/simple_add.c
- tests/ifs/ifs.c
This commit is a simple celan up of the sources by removing spotted trailing spaces.
> Remove trailing spaces.

- framework/forkfd/forkfd_linux.c
This can happen on Linux if we are ptracing the process, because ptrace(2) uses the wait() mechanism to get new events from the traced process. I don't know if anyone is using forkfd() to debug from the parent (it should be possible), but I expect that they use the wait functions directly instead of forkfd_wait() for the debugging work.
The problem is when something else traces our child processes. When a buggy debugger detaches from our process, waitid returns without setting si_signo (probably because SIGCHLD was never delivered). strace shows:
```
waitid(P_PIDFD, 19, {}, WNOHANG|WEXITED, {...}) = 0
```
And the child process never changes state.
> forkfd: Detect when waitid() returns with a reason not SIGCHLD

- framework/meson.build
- framework/sandstone_config.h.in
- framework/topology.cpp
Complements 6ac0642ba2b01943eb0823ada88f0693cebc0908 (PR #530).
> FW: Remove remnants of the triage feature

- .github/workflows/build.yaml
> CI: Bump Clang to 19

- framework/frequency_manager.hpp
> FW/frequency_manager: remove unused variables

- framework/sandstone.h
Runner might be used to instantiate test class (kept in test->data) and run it from static test context.
> Test runner class with additional CpuNotSupported/OsNotSupported

- framework/sandstone_ssl.cpp
As per https://systemd.io/ELF_DLOPEN_METADATA/
> FW/SSL: Add an ELF note indicating we may load OpenSSL

- .github/workflows/build.yaml
Add hwloc to the build workflow
> CI: Install hwloc in GitHub Actions for Linux and Windows

- framework/sandstone_opts.cpp
[ChangeLog][Framework] Removed `--test-range` option, which was not handled anyway.
> FW: remove dead code (--test-range option)

- framework/sandstone_context_dump.cpp
> FW/ContextDump: Update dump_xsave() to print the APX Extended GPRs

- framework/sysdeps/linux/kvm.c
Sometimes, unreleased versions of the kernel introduce bugs in some of the other leaves. This works around the problem, if any should happen, by only setting the ones that we need.
> FW/KVM: only set the CPUID leaves that truly matter to us

- framework/logging.cpp
Adjust expected size by the size of the init skip message for main threads which run init(). There's still a small potential issue with the same code potentially printing a different skip message, but it needs to be addressed separately and is, in fact, an indication of non-SMP machine or something badly broken.
Before:
```
result: skip
skip-category: CpuTopologyIssue
skip-reason: '2 threads on the same core are required'
time-at-end:   { elapsed:      3.999, now: !!timestamp '2025-05-16T18:39:26Z' }
test-runtime: 2.678
threads:
- thread: main
messages:
- test: mce_check
```
After:
```
result: skip
skip-category: CpuTopologyIssue
skip-reason: '2 threads on the same core are required'
time-at-end:   { elapsed:      4.000, now: !!timestamp '2025-05-16T18:38:44Z' }
test-runtime: 2.515
- …
```
> FW: Fix empty messages in main threads when a test was skipped.

- framework/selftest.cpp
> FW/Selftests: add a data-comparison test that randomly fails

- framework/topology.cpp
Instead of creating a new one on the heap and stored as a static `std::vector`.
> FW/Topology (fake): use the existing cpu_info[] array instead

- framework/topology.cpp
This will allow us to do some pre-processing before launching the detection and save the topology CPUID in the heap instead of in static (.bss) variables.
> FW/Topology: reorganize code to use a TopologyDetector class
